### ISSUE TITLE
Safetynet fix module is derping "at a glance"

### ISSUE THREAD

**Issue by oooompaloompa** [kdrag0n/safetynet-fix#108]
Safetynet fix module is derping "at a glance" on the latest stable pixel ROM, sunfish is the device I tested with. 
With SafetyNet module the at a glance settings get as shown in the attached SS.
At a Glance weather on home screen does not show up anymore until the the modules is turned OFF.
![Screenshot_20211021-152225](https://user-images.githubusercontent.com/92918626/138297652-87f2a770-c1f8-4e80-9907-52320e6764ba.png)
.

**Comment by kdrag0n** [comment]
Fixed in [v2.1.2](https://kdrag0n.dev/patreon/safetynet-fix/v2.1.2?utm_source=github) (for Riru) and [v2.2.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0?utm_source=github) (for Zygisk).
