### ISSUE TITLE
Zygisk breaks Riru in new Canary Magisk

### ISSUE THREAD

**Issue by pndwal** [kdrag0n/safetynet-fix#109]
Just a heads-up really.

While Riru and Zygisk (as well as USNF 2.x.x) were working nicely together in vvb2060 Alpha Magisk before todays builds, Riru is now is broken with Zygisk w/ latest TJW commits in both Alpha and TJW's new Canary Magisk.

John has just provided documentation for "Develping Zygisk Modules"

"The Zygisk API and sample module is online! Start developing and testing Zygisk modules with the latest canary release 😀"
https://github.com/topjohnwu/zygisk-module-sample

Hope it helps. PW

**Comment by osm0sis** [comment]
Worth noting when @kdrag0n does publish the new Zygisk rewrite of USNF then gms and unstable will actually need to be removed from the DenyList for the module to function correctly

**Comment by kdrag0n** [comment]
A new Zygisk version of Universal SafetyNet Fix is now available, so this is no longer an issue: https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0

**Comment by mxcxpx** [comment]
one time pay via Paypal?

**Comment by bjrnptrsn** [comment]
Does PayPal App allow adding to GPay with this new fix?

**Comment by username227** [comment]
Will this new version help with SafetyNet after Zygisk is activated in Magisk? Because activating Zygisk itself in Magisk breaks SafetyNet for me.

**Comment by meyerrj** [comment]
@bjrnptrsn  The 2.2.0 version fixed the Google Play store for me, but not GPay.  I just get a "Not set up" message near the NFC icon.

**Comment by osm0sis** [comment]
> @bjrnptrsn The 2.2.0 version fixed the Google Play store for me, but not GPay. I just get a "Not set up" message near the NFC icon.

As always, if you've failed SN at some point then that's stored in Play Services (i.e. where Google Pay actually runs from), so you'll have to wipe all data on Play Services after setting up the new module to get Google Pay passing again.

**Comment by meyerrj** [comment]
@osm0sis thanks for the reminder! I had tried clearing the cache, but yeah, it needed the full data wipe. Annoying to re-add cards, but it worked. :)

**Comment by osm0sis** [comment]
> Will this new version help with SafetyNet after Zygisk is activated in Magisk? Because activating Zygisk itself in Magisk breaks SafetyNet for me.

Yes, it should. In fact Play Services gms and gms.unstable need to not be in the DenyList so that the Zygisk USNF can load correctly.

**Comment by mxcxpx** [comment]
> @osm0sis thanks for the reminder! I had tried clearing the cache, but yeah, it needed the full data wipe. Annoying to re-add cards, but it worked. :)

So what exactly to wipe? Full data wipe? Factory wipe?

**Comment by meyerrj** [comment]
> > @osm0sis thanks for the reminder! I had tried clearing the cache, but yeah, it needed the full data wipe. Annoying to re-add cards, but it worked. :)
> 
> So what exactly to wipe? Full data wipe? Factory wipe?

On a Pixel 4a:  Settings -> Apps -> See All Apps -> Google Play services -> Storage & cache -> Manage Space -> Clear All Data

**Comment by KieronQuinn** [comment]
> @bjrnptrsn The 2.2.0 version fixed the Google Play store for me, but not GPay. I just get a "Not set up" message near the NFC icon.

Just my two cents on the "not set up" message too, sometimes it lies. I had that message, then tried using Pay anyway and it worked fine, and now shows the "hold to reader" message instead. The status probably just isn't updating somewhere and making a payment updates it. Best to use a self checkout machine to test though, it sometimes confuses checkout staff if a phone payment fails I find.

**Comment by mxcxpx** [comment]
i payed for the fix an it works so far.
g-pay has no more problem 
safetyNet passed success !!
