### ISSUE TITLE
Unsupported CPU architecture

### ISSUE THREAD

**Issue by emaborsa** [kdrag0n/safetynet-fix#11]
I am working on a Samsung A6 (sm-A600fn), trying to fix ctsProfile. Installing the Safetynet-fix v1.1.1 I get 
- Unsupported CPU architecture: armeabi-v7a
- Installation failed

What's wrong?

**Comment by emaborsa** [comment]
I apologize for the

**Comment by reemnamous** [comment]
I am having the same issue
