### ISSUE TITLE
weather at a glance  issues

### ISSUE THREAD

**Issue by diosvany** [kdrag0n/safetynet-fix#111]
weather at a glance stops working after ai enable universal safety fix i'm running android 12 with the lastest usf

**Comment by Didgeridoohan** [comment]
With "latest", to you mean v2.1.2/v2.2.0? Because they're supposed to have that fixed...
https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0?utm_source=github

**Comment by diosvany** [comment]
the thing is that i cant pass safetynet with zygisk so I'm using the latest USF before zygisk

**Comment by Didgeridoohan** [comment]
If you're not using the latest release (that works with Zygisk and also is available for Riru), that has your issue fixed already, you're just gonna have to live with it...

And you should probably close this issue ticket since it's not actually a problem.
