### ISSUE TITLE
Ulefone Armor 6e

### ISSUE THREAD

**Issue by anon97945** [kdrag0n/safetynet-fix#112]
i'm on lineageos 17.1 Android 10 8 August 2021. 
treble_arm63_bvS-userdebug 10 QQ3A.200805.001 eng.crossg.20210808.170014test-keys
with magisk 23000 and it does not work. 
Magisk tells me: 
safety basicintegrity -
ctsprofile -
evaltype BASIC

**Comment by kdrag0n** [comment]
As far as I'm aware, you will need to use [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf) to spoof a valid device profile (i.e. not the generic GSI device name and fingerprint).
