### ISSUE TITLE
Does version 2.2.0 support riru?

### ISSUE THREAD

**Issue by ender-zhao** [kdrag0n/safetynet-fix#113]

**Comment by KieronQuinn** [comment]
2.1.2 is for Riru, 2.2.0 is for Zygisk, as is detailed on the Patreon posts.

![image](https://user-images.githubusercontent.com/3430869/140656715-72247979-3580-4725-9f44-7eb1374f3a14.png)

**Comment by kdrag0n** [comment]
Yes, please use 2.1.2 if you want to use it with Riru. Thanks @KieronQuinn!
