### ISSUE TITLE
Module breaks screen off Google hotword detection

### ISSUE THREAD

**Issue by lavin-a** [kdrag0n/safetynet-fix#114]
When the module is activated, the "hey Google" hotword only works when the screen is on, check images for reference. I don't know if this conflicts with Google/GMS or the Qualcomm Voice assist app which is responsible for hotword detection.

Device: OnePlus 8 Pro OOS 11.0.9.9

With module:
![Screenshot_20211110-010008](https://user-images.githubusercontent.com/49375935/141084894-ba7665d2-2f0a-4361-a8c6-2b02a7ce0223.jpg)

Without module:
![Screenshot_20211110-041901](https://user-images.githubusercontent.com/49375935/141085977-03084f6a-7244-4f9c-bf3d-9645a300187d.jpg)

**Comment by kdrag0n** [comment]
This has already been fixed in [v2.1.2](https://kdrag0n.dev/patreon/safetynet-fix/v2.1.2?utm_source=github) (for Riru) and [v2.2.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0?utm_source=github) (for Zygisk).
