### ISSUE TITLE
Under-display fingerprint not working with 2.2.0

### ISSUE THREAD

**Issue by Jowat97** [kdrag0n/safetynet-fix#115]
Hello there,

after I installed the patreon version from safetynet-fix 2.2.0, the in-display fingerprint-reader isn't working anymore.
It doesn't show up anymore at all. And if pressed, nothing happens.

I have a Realme X2 Pro, running Android 11. Newest Magisk Canary (23014) is installed and no other modules/mods are installed.
However, the CTS-fix works (Safetynet already works, even without fix).

For me it seems like a similar issue as we had with the OnePlus devices, which was fixed in 2.1.1 by @osm0sis.

**Comment by Jowat97** [comment]
@kdrag0n @osm0sis fyi: The problem also occurs with the final GitHub release. And I can confirm that other Realme users have this issue as well. Also tried older canary versions of Magisk, but unfortunately no success. After uninstalling the module, fingerprint will work again. If you need any further information, feel free to ask. Hope this issue can be solved quickly. ☺️

**Comment by pardeepk21** [comment]
I'm using OnePlus Nord and the Riru version of safetynet-fix-2.1.0.zip still has fingerprint issue.

**Comment by osm0sis** [comment]
> I'm using OnePlus Nord and the Riru version of safetynet-fix-2.1.0.zip still has fingerprint issue.

Of course it does, the OnePlus device fix was included in 2.1.1. USNF for Riru 2.1.2 is out now, so either use that with Magisk stable, or USNF for Zygisk 2.2.0 with Magisk Canary.

**Comment by Jowat97** [comment]
@osm0sis How exactly? Have tried a lot of different things and still this problem occurs.
The safetynet-fix 2.2.0 includes multiple things, like Basic integrity bypass, CTS fingerprint spoof, force Basic evaluation, some device specific changes like for OnePlus or Samsung devices and so on.

However, most of this stuff is not necessary for the Realme X2 Pro. Basic integrity will pass even without fix. Also it only supports Basic evaluation and no hardware attestation, so no need to force it. And those device specific changes are also not necessary for the X2 Pro.
Would it be somehow possible to extract only the "CTS fix" from the module? Since the fingerprint issue may occurs from one of the other functions. If I could test the CTS-fix only and it would work, we could find out which specific function is the root for this problem.

**Comment by osm0sis** [comment]
Did it work with Magisk Stable 23000/Canary 23001 with MagiskHide? You could also try Canary 23015 and the MagiskHidePropsConfig module since your device passes basicIntegrity on its own.

**Comment by Jowat97** [comment]
@osm0sis Unfortunately Realme UI 2.0 doesn't work with 23000/23001. Earliest version supporting RUI 2.0 is 23010. But back then as I was still on RUI 1.0, I was using Magisk Stable and it worked perfectly with Magisk Hide. Basic Integrity and CTS Check passed without any issues.

I also already thought about using MagiskHidePropsConf. But using the fingerprint from a different device may cause some wired problems. And I have to check if the device fingerprint I'm spoofing has the same Security Patch level as mine etc. So it is way more complicated than this module. But yeah, if this issue can't be solved, I guess I have no other options. =/

Also thought about using Magisk Alpha from @vvb2060. Afaik, it still has build in MagiskHide.

However, as soon as the new Magisk Stable is released, I think many Realme Users will face this issue (maybe some other as well). So it would be nice if this could be somehow solved. I can try to contribute as much as I can.

**Comment by osm0sis** [comment]
You don't have to change the fingerprint in props config, it just has the old MagiskHide props as well.

**Comment by Jowat97** [comment]
@osm0sis Unfortunately it does not work. Tested it right now. MagiskHide props enabled, but CTS still fails. So I wanted to simulate a fingerprint and my device was listed, but only with RUI 1.0. Argh, I guess I need to wait until this somehow will get fixed.

**Comment by Jowat97** [comment]
@osm0sis @kdrag0n 
I have found out something interesting. MagiskHide Props Config will also brick my is-display-fingerprint, but only if I change the device-fingerprint within the prods-settings. Even if I choose my own device-fingerprint. It seems like, that if the device-fingerprint get changed, the in-display-fingerprint bricks. I also dumped the log: [propslogs.tar.gz](https://github.com/kdrag0n/safetynet-fix/files/7651295/propslogs.tar.gz)

This may helps to solve this issue.

Greetings.

**Comment by osm0sis** [comment]
Just saw https://github.com/kdrag0n/safetynet-fix/commit/f09cb3dd6e396e6b312a10c5dec65333aa8a2771#commitcomment-62230438 which may shed a little light on this.

So it doesn't work in system.prop, but does it work when set as a late prop?

**Comment by Jowat97** [comment]
> Just saw [f09cb3d#commitcomment-62230438](https://github.com/kdrag0n/safetynet-fix/commit/f09cb3dd6e396e6b312a10c5dec65333aa8a2771#commitcomment-62230438) from @byxiaorun which may shed a little more light on this issue.
> 
> So ro.boot.flash.locked=1 doesn't work on Realme in system.prop, but does it work when set instead as a late prop? Can someone test this idea?

Yes, I could test it. But how exactly can I set ro.boot.flash.locked=1 as late prop?
If you can tell me how, I can test it out and post my results.

**Comment by osm0sis** [comment]
With 2.2.0 or 2.1.2 installed go to /data/adb/modules/safetynet-fix and edit system.prop to remove `ro.boot.flash.locked=1`, then edit service.sh and first try adding it below the MIUI section with `maybe_set_prop ro.boot.flash.locked 0 1` and then reboot to see if that makes it work. If that still doesn't work then remove that line again and put it in the late props area below the OnePlus entry as `resetprop ro.boot.flash.locked 1` and reboot to see if that works. 🤞

**Comment by osm0sis** [comment]
I'll submit a PR as soon as I'm in front of my PC again later today! 🙌

**Comment by kdrag0n** [comment]
> @osm0sis Modifying ro.boot.flash.locked as maybe_set_prop doesn't work. However, setting it as resetprop does, thanks! =)
> I have created a zip file, where those modifications are already made, hope it's okay for you @kdrag0n 
> Patched safetynet-fix for Realme devices: [safetynet-fix-v2.2.0.zip](https://github.com/kdrag0n/safetynet-fix/files/7746746/safetynet-fix-v2.2.0.zip)
> 

Thanks for looking into it! I'll make a release later today with the fix.
