### ISSUE TITLE
Safetynet-fix no longer working

### ISSUE THREAD

**Issue by awshirley** [kdrag0n/safetynet-fix#116]
This was working until a few days ago.  Google made a change and this doesn't work any longer.

**Comment by pbanj** [comment]
https://twitter.com/topjohnwu/status/1457932566846062594?s=20
https://twitter.com/osm0sis/status/1457939659070361603?s=20

Give those a read

**Comment by username227** [comment]
> https://twitter.com/topjohnwu/status/1457932566846062594?s=20 https://twitter.com/osm0sis/status/1457939659070361603?s=20
> 
> Give those a read

Well, we knew it would happen....i hope that kdrag0n releases the newest version on github soon.

**Comment by pbanj** [comment]
install https://forum.xda-developers.com/t/module-magiskhide-props-config-safetynet-prop-edits-and-more-v6-1-2.3789228/ and see if it helps. i have that installed as i use some prop edits not related to safetynet and im still passing on my 5a

**Comment by osm0sis** [comment]
Here's a better Twitter thread for everyone: https://twitter.com/osm0sis/status/1460090655733170183

**Comment by AndDiSa** [comment]
Had the same issue on my Pixel 3a (running Android 12), but adding com.google.android.gms to hide list resolved the issue (at least for the moment)

**Comment by kdrag0n** [comment]
Closing as context has been provided above. I'm not personally aware of any new widespread failures in the last few days and it doesn't look like many have been reported in the support group, so this seems like a setup-related issue.
