### ISSUE TITLE
Crave TV detection

### ISSUE THREAD

**Issue by Nolij** [kdrag0n/safetynet-fix#118]
I understand this may be unrelated to SafetyNet and therefore not part of this project, but I don't know if it's SafetyNet or some other detection that's failing here.

The Crave app can still tell my phone is rooted.

Phone: OnePlus 7 Pro GM1917 12GB Model
Magisk: Latest canary w/ Zygisk enabled and manager hidden
USNF: latest 2.2 early access
Crave app is on Magisk DenyList
I pass SafetyNet according to YASNAC with BASIC attestation

Once again don't know if it;s SafetyNet that's failing or some other detection that they have for root, although I'm not sure how anything else could detect root considering I have MagiskHide via UNSF, Zygisk enabled, manager hidden, and the app added to the DenyList. Regardless, if it's not SafetyNet that's failing please feel free to close this issue as I'm sure that's not within the scope of this project.

**Comment by username227** [comment]
And Chase. Chase is the bane of my phone. :-(

**Comment by AllenChangMusic** [comment]
Try using one of the SafetyNet apps to check whether you pass SafetyNet. If so, then the detection is not based on SafetyNet and is outside of the scope of this module.

**Comment by Nolij** [comment]
> Try using one of the SafetyNet apps to check whether you pass SafetyNet. If so, then the detection is not based on SafetyNet and is outside of the scope of this module.

As stated I do pass according to other apps. My concern is this app could be somehow forcing hardware attestation

**Comment by AllenChangMusic** [comment]
That's not how it works. An app can't just fore hardware attestation. It's dependent on your device signature and whether google expects hardware attestation from given device, etc. So you won't pass SafetyNet in one app, and not another.
The checking of safetynet was more towards the other guy asking about Chase. 
Either way, for both of you guys, download Momo to check other things that could be being detected.
Nevertheless, as long as SafetyNet is being passed in any of the checkers, the problem remains outside the scope of this module.

**Comment by Nolij** [comment]
> That's not how it works. An app can't just force hardware attestation. It's dependent on your device signature and whether google expects hardware attestation from given device, etc. So you won't pass SafetyNet in one app, and not another. The checking of safetynet was more towards the other guy asking about Chase. Either way, for both of you guys, download Momo to check other things that could be being detected. Nevertheless, as long as SafetyNet is being passed in any of the checkers, the problem remains outside the scope of this module.

Alright. Can you link me this "momo" you're referring to? I can't find it.

**Comment by AllenChangMusic** [comment]
https://www.coolapk.com/apk/io.github.vvb2060.mahoshojo
Apparently it's the strongest detection app.
There is a Riru module called MomoHider to fix some of the issues, but ofc if you're using Zygisk, then you're out of luck

**Comment by DavidBerdik** [comment]
@Nolij @username227 

In many cases, apps detect root by checking for the Magisk default package name as well as other third party apps that rely on root access in order to work properly. I would recommend trying out [Hide-My-Applist](https://github.com/Dr-TSNG/Hide-My-Applist). It's an Xposed module that, as the name implies, allows users to hide apps from being detected by certain apps. To use this app, you will need to install the LSposed Magisk module, which itself depends on Riru. The app also ships with its own Magisk module to make the hiding even more effective.
