### ISSUE TITLE
Version 2.2 Breaks Lsposed

### ISSUE THREAD

**Issue by username227** [kdrag0n/safetynet-fix#119]
Hi, I thought I would share. I just installed the latest version 2.2.0 from github that you released.

After doing so, Lsposed breaks. I am using the preview version of Lsposed for Zygisk, 1.6.3 (6228). It crashed completely and won't start up. After downgrading back to 1.2, it worked again.

Needless to say, the two modules should be able to coexist. Not sure if it's an issue with your module or lsposed, but I wanted to make you aware. Thanks.

**Comment by pndwal** [comment]
Both working fine for me on RN8T.

**Comment by AllenChangMusic** [comment]
Works for me on Pixel6Pro

**Comment by basamaryan** [comment]
Working fine on RN10P

**Comment by kdrag0n** [comment]
Are you using Magisk Canary 23014 (or newer)? This exact issue was fixed in that version.

**Comment by username227** [comment]
Yes, you're right - I just figured this out right before you posted your reply but before I had a chance to close the issue. The canary channel wasn't activated in magisk so i was unaware that the canary version was updated. Sorry about that.
