### ISSUE TITLE
Biometrics on OP7 pro (android 11)

### ISSUE THREAD

**Issue by diiegg** [kdrag0n/safetynet-fix#12]
Biometrics works in the phone if I want to unlock the screen, the problem is when I try to add x app biometric auth on setting the app donst d recognize the biometrics.

I test the phone and the biometrics are not recognized.
magisk module says that biometrics are not sported on the device or not enabled.

**Comment by kdrag0n** [comment]
Please test the new solution in #13 and continue discussion there.
