### ISSUE TITLE
Could Riru safetynet-fix work with Canary?

### ISSUE THREAD

**Issue by pndwal** [kdrag0n/safetynet-fix#120]
As 2.2.0 (RN8T, Magisk 23014) allows SafetyNet to pass with or without denylist enforced, I wonder if Riru solution could also be made to work in Canary (fails basic integrity check for me) and future public releases without MagiskHide / hidelist for use where users enable Riru / disable Zygisk?

I'm guessing it may be a simple matter of implementing similar solution to hide root from Play Services safetynet (and main process if needed), but please say if I'm wrong...

I'm guessing that having this option will be valuable to some wishing to use certain Riru modules and may become even more valued if banks start detecting Zygisk as Riru is already hideable. A hide list could also be provided for by Rootcloak mod or similar. 😛

**Comment by kdrag0n** [comment]
Riru will be dropped

**Comment by kdrag0n** [comment]
Riru support will be dropped once Zygisk is in stable Magisk, so I don't think this is worth pursuing. I think the ecosystem will generally move onto Zygisk after that.

**Comment by pndwal** [comment]
Thanks for your response, and valued work! 👍

Since some are concerned that banks etc will start detecting Zygisk (can't be hidden at present) and some need currently Riru-only solutions, some users are opting to stay with Riru solutions even on current Canary Magisk.

Magisk of course makes it a choice; Zygisk modules are disabled with Riru active and vice versa. LSPosed now offers both Zygisk and Riru solutions also.

Alt least while the choice exists, please _consider_ offering solutions for the two configurations as some are bound to take the Riru option for some time, and more will likely revert to Riru configuration if Zygisk proves unhidable in the long term.

Even in the short term, allowing USNF 2.1.x to work without MagiskHide would make it useful for Canary users choosing to stay with Riru for whatever reason. These are currently limited to older hiding solutions as 2.1.2 can only work for (old) Stable Magisk users...

Further, I'm guessing John may well have envisaged a continued demand for Riru when deciding to disable it only in if Zygisk is enabled...
