### ISSUE TITLE
Not working on Redmi note 8

### ISSUE THREAD

**Issue by Swilla66** [kdrag0n/safetynet-fix#121]
I flashed the file using magisk canary 23014. It isn't working. Only Basic integrity is passed. CTS remains failed.

Please help.
My ROM is pixel experience on Android 12.
Android security update: 5th October 2021.

**Comment by Didgeridoohan** [comment]
It's likely that either the ROM isn't using a certified fingerprint, or if it is the security patch date doesn't match the print.

Use MagiskHide Props Config.

**Comment by pndwal** [comment]
Pixel experience doesn't work as they manipulate props in pre-built utils. Must be fixed by ROM Dev.
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-85580011

**Comment by Swilla66** [comment]
Thank you @Didgeridoohan  and @pndwal .
I'll have to wait for the ROM Devs.

**Comment by pndwal** [comment]
> Thank you @Didgeridoohan and @pndwal . I'll have to wait for the ROM Devs.

As @Didgeridoohan mentioned, if it's simply lacking certified fingerprint you can fix yourself with his MHPC module. If, as I suspect, you have pre-built utils issue (I think most / all? PE users do), you probably need to inform ROM Dev of conflict with USNF module to see it resolved, or use different custom ROM.

Either way it's out of scope for USNF so you should close this issue. All best, PW

**Comment by kdrag0n** [comment]
Closing as this issue doesn't seem relevant to the module — thanks everyone for helping diagnose the issue!
