### ISSUE TITLE
profile match not working on Android 10 (zygisk)

### ISSUE THREAD

**Issue by ezxpro** [kdrag0n/safetynet-fix#128]
I have a Redmi 7, it's an Android 10 ROM, zygisk is enabled and the 2.2.0 version of this module  is not working as it should. See ![Screenshot_20211213-075021.jpg](https://user-images.githubusercontent.com/15344931/145800229-e3117981-517c-4026-8b6e-7e3086ba0b4e.jpg)

Logcat: https://drive.google.com/file/d/1lbwwaZdCNz6rJUkgZ4UiHNX9cTj694-7/view?usp=drivesdk

**Comment by kdrag0n** [comment]
Please try following https://t.me/proton_projects/32037 and https://t.me/proton_projects/33200 to fix the issue. Universal SafetyNet Fix only handles hardware attestation and basic properties.
