### ISSUE TITLE
Basic integrity and CTS fail - Found the solution, posted in comments

### ISSUE THREAD

**Issue by CodeXTF2** [kdrag0n/safetynet-fix#131]
Phone: HD1900
Using Zygisk on latest version (as of now) of this project. Interestingly it was working fine for a while yesterday, but then stopped working overnight. No new modules or software were installed.

**Comment by osm0sis** [comment]
Second paragraph of the README. If you can't get it to pass basic then that's beyond the scope of this module.

**Comment by CodeXTF2** [comment]
Update: seems to have fixed itself. Will update here if I ever find out the cause of this, but closing my issue for now. Sorry for the unrelated issue. :)

**Comment by CodeXTF2** [comment]
Update: FOUND THE ISSUE! Stock systemless hosts module causes basic integrity to fail. Leaving this here for anyone who faces this issue in the future.

**Comment by osm0sis** [comment]
Weird. Doesn't make it fail here.

**Comment by CodeXTF2** [comment]
Interesting. I just did it and it seems repeatable for me. Oh well.
