### ISSUE TITLE
This is not issue, just add "Remove Google Play Store from DenyList" for Zygisk SafetyNet Fix to README.md

### ISSUE THREAD

**Issue by HuskyDG** [kdrag0n/safetynet-fix#132]
Since everyone thought DenyList = MagiskHide, so after they flash SafetyNet Fix and reboot, they will add Google Play Store to denylist like they do with riru one and Zygisk will not load SafetyNet Fix for Google Play Store, SafetyNet will fail anyway.

**Comment by CodeXTF2** [comment]
Play store is in my denylist and I pass safetynet with this module just fine. I think you mean google play services?

**Comment by HuskyDG** [comment]
> Play store is in my denylist and I pass safetynet with this module just fine. I think you mean google play services?

post-fs-data.sh of zygisk usnf, will auto remove gms from denylist, overwise zygisk will not load module for gms, i think many people will add gms to denylist after flash module and reboot
Can you check if gms is in denylist

![Screenshot_2021-12-26-15-58-12-903_me zhanghai android files](https://user-images.githubusercontent.com/84650617/147403531-ec40aa43-2a45-408d-b857-0916c3a25847.jpg)

**Comment by HuskyDG** [comment]
![Screenshot_2021-12-26-15-58-12-903_me zhanghai android files](https://user-images.githubusercontent.com/84650617/147403571-e8e30139-e026-4271-a9b1-b148d7f56ec3.jpg)

**Comment by osm0sis** [comment]
Play Store in DenyList has no effect on SafetyNet or USNF's functionality.
