### ISSUE TITLE
v2.1.3 (Riru) not wokring on my Note 20 ultra A12

### ISSUE THREAD

**Issue by Conan179** [kdrag0n/safetynet-fix#133]
Hi i have a problem, on this rom https://forum.xda-developers.com/t/31-12-21-n986b-i-n985f-ds-i-dr-ketan-rom-i-oneui-4-0-i-oneui-3-1.4154487/ the safetynet-fix for riru v2.1.3 dosnt work.
Is there an opportunity to get help here?
![2022-01-01 16 30 58](https://user-images.githubusercontent.com/1906242/147939295-57cbb82b-11f1-4237-9196-969e6751a966.jpg)

**Comment by Didgeridoohan** [comment]
I see two things in the instructions for that ROM:

- There's a SafetyNet fix included in the ROM.
- Don't use any other fix.

**Comment by Conan179** [comment]
the fix from the rom is the same https://github.com/kdrag0n/safetynet-fix/releases/tag/v2.1.3 both are not working.

**Comment by mgkibria** [comment]
Failed on my K20 Pro, xiaomi.eu 21.11.24
Running with Riru v26

**Comment by kdrag0n** [comment]
You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481
