### ISSUE TITLE
Safety net fix does not work lineage os 17.1 (cts profile)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [kdrag0n/safetynet-fix#134]
I have a Motorola edge and I have been trying to pass safety net. I have tried everything from spoofing device fingerprint to resetting gapps data and nothing works. Magisk hide is enabled for the google play store, google services framework, and google play services. 
I think it might be my other magisk modules, but none of them seem like possible issues.

**Comment by Etaash-mathamsetty** [comment]
And I obviously have riru installed

**Comment by HuskyDG** [comment]
If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build

**Comment by ALI5BABA** [comment]
#

> 

> [https://drive.google.com/file/d/1wH3daNDu0KYDOnSVhiooT9DPdvANBPlF/view?usp=drivesdk](https://drive.google.com/file/d/1wH3daNDu0KYDOnSVhiooT9DPdvANBPlF/view?usp=drivesdk)

**Comment by ALI5BABA** [comment]
https://drive.google.com/file/d/1wH3daNDu0KYDOnSVhiooT9DPdvANBPlF/view?usp=drivesdk

**Comment by ALI5BABA** [comment]
Flash this inshaAllah your CTS_PROFILE issue will be fix

**Comment by Etaash-mathamsetty** [comment]
> https://drive.google.com/file/d/1wH3daNDu0KYDOnSVhiooT9DPdvANBPlF/view?usp=drivesdk

I don't have access to that

**Comment by Etaash-mathamsetty** [comment]
> If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build

I have tried that too, it dosen't work

**Comment by HuskyDG** [comment]
> > If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build
> 
> I have tried that too, it dosen't work

Refash the stock ROM, maybe caused by your Custom ROM

**Comment by Etaash-mathamsetty** [comment]
> > > If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build
> > 
> > 
> > I have tried that too, it dosen't work
> 
> Refash the stock ROM, maybe caused by your Custom ROM

it works on the stock rom obviously, i used the stock rom for a year until the warranty runned out

**Comment by HuskyDG** [comment]
> > > > If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build
> > > 
> > > 
> > > I have tried that too, it dosen't work
> > 
> > 
> > Refash the stock ROM, maybe caused by your Custom ROM
> 
> it works on the stock rom obviously, i used the stock rom for a year until the warranty runned out. The stock rom is more broken and buggy compared to the custom one, so I don't want to flash it there is also no guarantee that the stock rom + magisk hide and stuff will not cause the safety net errors to return

Pass SafetyNet is no mean from now. I don't ever Pass SafetyNet and I can still use banking app...
Also Google Play Store will replace SafetyNet API with Play Integrity soon

**Comment by Etaash-mathamsetty** [comment]
> > > > > If you don't pass ctsprofile SafetyNet then you have incorrect fingerprint build, use MagiskHide Props Config to replace your fingerprint build
> > > > 
> > > > 
> > > > I have tried that too, it dosen't work
> > > 
> > > 
> > > Refash the stock ROM, maybe caused by your Custom ROM
> > 
> > 
> > it works on the stock rom obviously, i used the stock rom for a year until the warranty runned out. The stock rom is more broken and buggy compared to the custom one, so I don't want to flash it there is also no guarantee that the stock rom + magisk hide and stuff will not cause the safety net errors to return
> 
> Pass SafetyNet is no mean from now. I don't ever Pass SafetyNet and I can still use banking app... I don't use Google Pay Also Google Play Store will replace SafetyNet API with Play Integrity soon

i bet that's going to be even harder to spoof

**Comment by kdrag0n** [comment]
You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481

**Comment by Etaash-mathamsetty** [comment]
> You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481

is this a recent change, becuase I have been using easy effects for a while and it wasn't like this

**Comment by Etaash-mathamsetty** [comment]
> You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481

I have tried all of those things except disabling all magisk modules

**Comment by Etaash-mathamsetty** [comment]
Alright it finally works
