### ISSUE TITLE
Hiding does not work with the CIB Bank application.

### ISSUE THREAD

**Issue by Alacika** [kdrag0n/safetynet-fix#135]
Hi!

Hiding does not work with the CIB Bank app: https://play.google.com/store/apps/details?id=hr.asseco.android.intesa.isbd.cib

I have tried both v2.2.1 (Zygisk) and v2.1.3 (Riru)+Riru, but the problem is the same. Safetynet check are passed, but when the Cib Bank app starts, it warns that the phone is rooted. But the CIB Bank app never worked with Magisk Hide either. Works fine with other banking apps.

I have the OnePlus 3T and the rooted factory Android 8.

Sorry for my poor English!

**Comment by crok** [comment]
> Sorry for my poor English!

Perhaps in hungarian? In case yes, [here's a good forum](https://mobilarena.hu/tema/magisk/friss.html) with a [good tutorial](https://mobilarena.hu/tema/magisk/index.html) for you. I guess it's not detecting root or Magisk itself but some indirect signs or traces of having a tampered system. My two cents.. _Üdv a PH!-ról._

**Comment by Alacika** [comment]
> > Sorry for my poor English!
> 
> Perhaps in hungarian? ... _Üdv a PH!-ról._

Köszönöm! :-)

**Comment by Alacika** [comment]
Sorry, the problem was caused by an undefined configuration issue!
