### ISSUE TITLE
FEATURE REQUEST:  Magisk Modules Alt Repo

### ISSUE THREAD

**Issue by Jon8RFC** [kdrag0n/safetynet-fix#136]
It would be great to add over there:
https://github.com/Magisk-Modules-Alt-Repo/submission

Works with fox's magisk module manager.

**Comment by osm0sis** [comment]
Orrr it could use the new Magisk module JSON feature and update itself without needing to be in any repo. 🤘

**Comment by CRCinAU** [comment]
Hahaha - I've had this on my to-do list to add this comment. The JSON / Magisk update process should be trivial to complete...

Documented here: https://topjohnwu.github.io/Magisk/guides.html

**Comment by kdrag0n** [comment]
Closing in favor of #140.

**Comment by Jon8RFC** [comment]
I think it'd still be great if it's in one of the module depots, because then people can search for it alongside other modules in one centralized place, rather than going out and looking for it.
It'd be good for avoiding bad/confusing search results in google as well.  I've yet to get a tainted module (as far as I know) from searching for the official source, but I'm sure they exist, or will exist in the future, just like tainted apks exist in those various backup sites.
