### ISSUE TITLE
device rebooting after apply safetynet module

### ISSUE THREAD

**Issue by lolinajdi** [kdrag0n/safetynet-fix#137]
hello i have issues when i use this module issues is after applying this safetynet fix the device some time's rebooting randomly i don't know what is problem.

my device info:

samsung galaxy s9+ 

android 10
 
rom is official rom not custom rom.

**Comment by VladWinner** [comment]
I had this problem on A11 (One UI 3.1), but disappeared with the upgrade to A12 (One UI 4.0)

**Comment by kdrag0n** [comment]
Please run `adb logcat` from a computer when it reboots.

**Comment by kdrag0n** [comment]
Closing due to lack of logs.
