### ISSUE TITLE
ctsProfile BASIC on LineageOS

### ISSUE THREAD

**Issue by ycomiti** [kdrag0n/safetynet-fix#138]
![Screenshot_20220126-005831_Manager](https://user-images.githubusercontent.com/94963509/151079865-c44c30be-3dde-4a39-b013-fa595b71d0b6.png)

**Comment by ycomiti** [comment]
Fixed with MagiskHide Props Config.
Sorry for disturbing.

**Comment by mmvanheusden** [comment]
Same issue here, gonna try installing that props config module as well.
