### ISSUE TITLE
Not working with google play Android 12 L (beta) pixel 4A 5G

### ISSUE THREAD

**Issue by templatetuners** [kdrag0n/safetynet-fix#139]
latest Magisk 24, checked everything from google, restarted, cleared cache..
In play store under Play Protect certification I have Devices is not certified.

**Comment by RAYs3T** [comment]
Having the same on a OnePlus 9 Pro.
* Magisk v24
* safetynet-fix-v2.2.1

If I check the attestation it's basic and works, but if I look in the PlayStore it says "device not certified".

**Comment by crok** [comment]
> If I check the attestation it's basic and works, but if I look in the PlayStore it says "device not certified".

In Magisk -> Hide Magisk app with random package ID + turn on Zygisk + Enforce DenyList + in DenyList -> upper right corner menu -> show system apps -> look for Google Play Services -> tick com.google.android.gms & com.google.android.gms.unstable and then delete all data of Google Play Services / Google Services Framework and Google Play Store, too, then reboot. My two cents.

**Comment by RAYs3T** [comment]
@crok Thanks! - I can confirm that this fixes the issue for the **Play Store**. Deleting the data before reboot was key.

Setting `com.google.android.gms` & `com.google.android.gms.unstable` on the denyList **is not required** and is even being automatically remove at boot by the `safetynet-fix` (see: https://github.com/kdrag0n/safetynet-fix/issues/132#issuecomment-1001132029)

Only issue which remains now is that Google Pay says that the device is "not qualified". Other apps do work perfectly now for me.

**Comment by crok** [comment]
> @crok Thanks! - I can confirm that this fixes the issue for the **Play Store**. Deleting the data before reboot was key.
> 
> Setting `com.google.android.gms` & `com.google.android.gms.unstable` on the denyList **is not required** and is even being automatically removed at boot by the `safetynet-fix` (see: [#132 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/132#issuecomment-1001132029))
> 
> Only issue which remains now is that Google Pay says that the device is "not qualified". Other apps do work perfectly now for me.

Great news. Guess I would delete the data of GPay as well to start over again from scratch.. just like GPlay..

**Comment by crok** [comment]
> @crok I did this before, after reboot those two are unchecked

Yeah, I forgot about issue #132 and the fact that USNF will untick it - sorry. But the rest is still standing.

**Comment by osm0sis** [comment]
G Pay works too, you just have to clear all data for Google Play services. This issue should be closed.
