### ISSUE TITLE
There is support for Android 7.x?

### ISSUE THREAD

**Issue by PANCHO7532** [kdrag0n/safetynet-fix#14]
I have a cellphone with Android 7.1 that it doesn't have any 8.x upgrade in plan. This patch can be used? If it isn't, there will be support for 7.x versions soon?

**Comment by Didgeridoohan** [comment]
Just to make clarify: are you sure you need it? Many devices that old do not have the necessary hardware to make a hardware backed key attestation check.

**Comment by PANCHO7532** [comment]
How do i know if i need it? I mean, for pass that check

**Comment by Didgeridoohan** [comment]
If you do a SafetyNet check in the Magisk app it'll tell you if evalType is hardware or basic. If it's basic you don't need the module.

**Comment by PANCHO7532** [comment]
What if it says "N/A"?

**Comment by Didgeridoohan** [comment]
In that case you probably don't need it either.

**Comment by PANCHO7532** [comment]
Hmm, in that case, do you recommend a method for bypassing the check, since it don't indicates that it uses either Basic or Hardware?

**Comment by Didgeridoohan** [comment]
If you want to pass SafetyNet I recommend that you start by finding out why there's an error with your SafetyNet check... But this is getting way off-topic for the issue section of this module. My suggestion is that you go to XDA and ask for help there instead.

**Comment by kdrag0n** [comment]
> If you do a SafetyNet check in the Magisk app it'll tell you if evalType is hardware or basic. If it's basic you don't need the module.

That's not actually true anymore. On devices not specifically whitelisted for hardware attestation, evalType will be reported as BASIC even if it's using key attestation, and this module will still be necessary.

The surefire way to check is by searching for messages containing `keystore` in logcat while performing an attestation.

**Comment by kdrag0n** [comment]
The current plan for supporting Android 7 is the new shim solution, so I'm merging this into #13 as well.
