### ISSUE TITLE
'Module suspended because Zygisk is not enabled', but it is...

### ISSUE THREAD

**Issue by jeancarlosna** [kdrag0n/safetynet-fix#141]
![WhatsApp Image 2022-01-29 at 18 50 07](https://user-images.githubusercontent.com/33769125/151678663-dcbbd1c8-4cc1-422a-b681-7acd80cabdfb.jpeg)
![WhatsApp Image 2022-01-29 at 18 50 11](https://user-images.githubusercontent.com/33769125/151678671-fca7ef1d-5a55-42a5-8892-cd14cde4f8fb.jpeg)
![WhatsApp Image 2022-01-29 at 18 50 15](https://user-images.githubusercontent.com/33769125/151678674-8b8133c9-68ee-4cec-a32c-58b43a1d88b6.jpeg)
![WhatsApp Image 2022-01-29 at 18 55 22](https://user-images.githubusercontent.com/33769125/151678776-5e15a808-05cb-444f-ad3a-3694fc8ed70b.jpeg)

"
I'm aware that exist a Riru and a Zygisk version and I'm using the right one. The Magisk app I'm using is the one I found in this thread -> https://github.com/topjohnwu/Magisk/issues/4174 -> https://github.com/topjohnwu/Magisk/files/7958690/app-debug.zip
I'm using this magisk version since NO OTHER version that has Zygisk recognize my root, despite other root aplications I've set before are still working. Every other Magisk(with Zygisk) version says N/A by 'Installed' option under Magisk first tab. 

Phone is a Samsung S7 SM-930F.

**Comment by jeancarlosna** [comment]
Btw, the magisk app that i've downloaded from that thread recognize root and offer zygisk in settings, but even if I enable it, in magisk app first screen still says Zygisk: No

**Comment by Yuzyuz01** [comment]
Same with my device Galaxy Note 8
Zygisk still No, but it already enabled, reboot still dont get the zygisk work (still no)
Bank Apss recognised the root (zygisk no work)
Please any advice, thank u

**Comment by chaoscreater** [comment]
Same issue, Galaxy S8+. Magisk v24 works fine on my other devices, just now S8+.

**Comment by kdrag0n** [comment]
Does it still show "Zygisk: No" if you disable Universal SafetyNet Fix? (yes, disable it even though it appears to be "suspended" already)

**Comment by Yuzyuz01** [comment]
> Does it still show "Zygisk: No" if you disable Universal SafetyNet Fix? (yes, disable it even though it appears to be "suspended" already)

I dont have any universal safstynet fix

**Comment by jeancarlosna** [comment]
> Does it still show "Zygisk: No" if you disable Universal SafetyNet Fix? (yes, disable it even though it appears to be "suspended" already)

Yes, still show no

**Comment by kdrag0n** [comment]
In that case, this is most likely a Magisk issue, not Universal SafetyNet Fix's fault. It would be an issue with this module if enabling the module causes Zygisk to break.

**Comment by Master3lwa** [comment]
``

**Comment by LeeBinder** [comment]
I suddenly encountered this issue, too, in my old phone after removing the SIM card because I'm only making carrier calls with my new phone. Seems Magisk 24.3 requires a SIM card for Zygisk to activate.

I was eventually able to solve this by installing **Magisk Canary** ([direct download latest apk](https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk) | [version info](https://github.com/topjohnwu/magisk-files/blob/master/canary.json)), reboot, voila - Zygisk enabled again, LSPosed (Zygisk) running, and all [..]posed modules working 👍

**Comment by bhgraham** [comment]
> Does it still show "Zygisk: No" if you disable Universal SafetyNet Fix? (yes, disable it even though it appears to be "suspended" already)

So I am having this issue on a raspberry pi 400, Zygisk is Yes on the Home tab but when I enable USNF it says incompatible.  When you asked this question, what would have been the fix in my case?

**Comment by ChuongPham** [comment]
The message "**Module suspended because Zygisk is not enabled**" is still showing on mobile devices running Android 8 - particular Samsung mobile devices. This is what I get:

![zygisk1](https://user-images.githubusercontent.com/7285620/180141600-32ab0bcf-deb1-4ca5-b148-b790ec232024.jpg)

and this:

![zygisk2](https://user-images.githubusercontent.com/7285620/180141615-0eb912ca-ae29-42b9-9ae7-3df2856f0131.jpg)

Universal SafetyNet Fix worked despite the error shown in Magisk as Google Play reported that these affected mobile devices are "certified"- meaning they would work with banking apps, streaming apps (like Netflix), etc.

It would be nice to get this issue fixed for the sake of completeness though. I don't know whether this is a Zygisk or a Magisk issue!

**Comment by TheRealChickon** [comment]
Hello from 2023 on a galaxy s10 I encountered this Issue upon installing magisk delta but reverting to normal magisk again.
To fix it I simply restored magisk again in the settings and then rehid it

**Comment by cyberalt1** [comment]
Please reopen, still an issue in 2025.

**Comment by uuI-l3bnVb** [comment]
Agreed. It may be lack of sim card in this instance but I don't understand why that would be a blocker.

**Comment by DoYouKnowMyNamePlz** [comment]
Absolutely an issue still

**Comment by ghost** [comment]
I updated Magisk through the app, forgot to disable all installed modules, so Zygisk wasn't "enabled" for me. I just toggled all modules off, rebooted and Zygisk is now enabled. I toggled all the installed modules I have and rebooted the phone again, and Zygisk stays enabled. I'm on Android 14.

**Comment by ghost** [comment]
> I updated Magisk through the app, forgot to disable all installed modules, so Zygisk wasn't "enabled" for me. I just toggled all modules off, rebooted and Zygisk is now enabled. I toggled all the installed modules I have and rebooted the phone again, and Zygisk stays enabled. I'm on Android 14.

Found one module that would give me an error, 'Systemless Hosts' ver 1.0

All other Modules running. 

![Image](https://github.com/user-attachments/assets/0a121753-53b3-4b5d-965c-c367e2ded758)
![Image](https://github.com/user-attachments/assets/7b230da1-d451-4610-ace7-89e562760791)

**Comment by ghost** [comment]
*update

Zygisk now seems to be operational after finding an update/fork for Systemless Hosts. I noticed some users have Systemless Hosts ver 1.0 installed. Check to see if your modules have updates or forked versions that have compatibility.

I'm on Android 14  Sept. 1 2024 build UP1A.231005.007.A546EXXS9CXH7

![Image](https://github.com/user-attachments/assets/e0368ef3-c79a-4e45-96c9-38c467ca896b)
![Image](https://github.com/user-attachments/assets/88b3d864-fdb8-4433-ac29-376aa291d136)

**Comment by immortal-soze** [comment]
if installed the JsHook module the magisk can do, first remove the Jshook module and LSPosed from the magisk reboot the device , most propably will be fixed. if doesn't fix remove the all modules one by one and reboot the device and you can see which modules making the issue. i solved like that.
