### ISSUE TITLE
Google play services automatically untick in zygisk configure list after reboot

### ISSUE THREAD

**Issue by random2907** [kdrag0n/safetynet-fix#142]

**Comment by kdrag0n** [comment]
Intended behavior. DenyList will be applied to Play Services anyway.

**Comment by jd1900** [comment]
It is quite confusing.

Now, I now there is no problem. But still a bit confusing for users who don't know about it.
Is it possible to change this behaviour?

Otherwise, in case of not be able to change, is it a problem to add to deny list when rebooting? Or it doesn't matter at all?

**Comment by kdrag0n** [comment]
> It is quite confusing.
> 
> Now, I now there is no problem. But still a bit confusing for users who don't know about it.
> Is it possible to change this behaviour?

No, it's not possible for Zygisk modules to load for apps in the DenyList.

> 
> Otherwise, in case of not be able to change, is it a problem to add to deny list when rebooting? Or it doesn't matter at all?

Adding Play Services to the DenyList will break SafetyNet as soon as the app restarts, because the module won't be able to load.
