### ISSUE TITLE
Phone freezes at Samsung logo after the installation and reboot of this module.

### ISSUE THREAD

**Issue by AnonymousBX01** [kdrag0n/safetynet-fix#148]
So I installed the latest Riru version of this module (v2.1.3), as it is the only that would actually work on my phone.

When that happened, I inmediately went to TWRP recovery and deleted this module folder from my Magisk directory.

But after restarting to System and passing the Samsung logo, just keeps in a black screen, like the UI won't even appear.

I can only see the touches (that I had enabled in developer options) and keep pressed the power option until the Power Off and Restart options appear. Nothing else. This never happened to me before. Quite strange, ngl.

So I wanna know, **what else I've got to delete from that module?** I didn't install anything else or touch nothing more than the installation of this Safetynet Fix module from the release .zip (the Riru one), so it cannot be anything, but just fault of this module messing around somewhere else. **Which files are left to delete, in order to get it as nothing happened?**

If I fix it by my own, I'll let you guys know, but until then, please help me. I don't wanna have to delete the entire Magisk, factory reset my phone, and/or something like so. I didn't really do a backup, as I thought the worst that would happen is the softbrick/bootloop, and that I could fix it the way I did (deleting the module folder from Magisk folder, but as I say, it keeps the same, still sure that this module f*cked up something that I haven't found yet).

I can provide more details if needed.

Thanks in advance.

Edit: So the only way I fixed it was entering Safe Mode (which did the phone boot normally) and uninstalling Magisk, but each time I reinstall it, the same problem appears, so we now know it's something related to Magisk (obviously). I'll probably have to delete all the data and the old files, as any other module, and check if that works...

Final Edit: The only way to fix it was deleting the Riru module entirely, which deleted the other modules I had installed and personally didn't even want to have removed them, but that's how life works.

Thank you all for the help... (Sarcasm)

Y'know... I would have been happy if you let me know the installation paths that this module used, which is what I was claiming from the beginning and as only deleting the module didn't even work. Or even if there was some detailed guide of Wiki I would have always appreciated it (THERE IS NOT, THAT'S A BIG PROBLEM). There is not even notice that installing it can screw up your phone the way it made with mine, so this should have worked as a reported bug. But it's still the same, no one has paid attention.

Despite being an obvious risk for me installing this, as with any other module, and that if I f*cked up (which was the case), I like to investigate and fix things by my own, for inexperienced people would be very good if the Dev spent 5 seconds just to warn... But the problem still is that **no one even wanted to help me out.**

I would close this issue, but I want to know if at least @kdrag0n is even going to notice me at some point.

**Comment by BenjaminVanRyseghem** [comment]
I got more or less the same issue. But I have to keep hard rebooting my phone until the magisk extensions aren't logged anymore. From there I can re-setup my phone/magisk.

Massive pain in the ass, and pretty sad that the maintainer didn't answer yet 😕

**Comment by kdrag0n** [comment]
Please get logs from a computer by running `adb logcat > issue.log` and uploading the file here.

Personal/private information may be present in the log, so feel free to redact it or PM it (referencing this issue) on Telegram.

**Comment by AnonymousBX01** [comment]
> Please get logs from a computer by running `adb logcat > issue.log` and uploading the file here.
> 
> Personal/private information may be present in the log, so feel free to redact it or PM it (referencing this issue) on Telegram.

You are be replying @BenjaminVanRyseghem, am I right? If not, then please notice that I had this problem a while back ago, already fixed it reproducing the steps, and of course I'm not gonna reproduce the steps again. This could be already closed by my part, but if Benjamin still has this problem, you should help him in a better way. I don't even think a logcat is necessary in the first place.

As I won't really provide a logcat, would you at least answer my biggest doubt, which was: Is it caused by something related by any other file or folder being used by this module other than the actual module folder? (Clearly yes, and it's related to Riru) And if so, where and which are those, in order to delete them without deleting Riru itself? Or wouldn't it get fixed without deleting Riru completely? And if so, why exactly? Talk to me in a technical way, even if I don't understand it at all, that's all I want to know.

**Comment by BenjaminVanRyseghem** [comment]
based on the pain it is to get rid of this situation, and the fact that I can't use my phone for hours or days, I'm not really prone to do it again if it's to have a "saved reply" after 40 days...

**Comment by AnonymousBX01** [comment]
> based on the pain it is to get rid of this situation, and the fact that I can't use my phone for hours or days, I'm not really prone to do it again if it's to have a "saved reply" after 40 days...

@BenjaminVanRyseghem Totally agree with you, I'm closing this then.
