### ISSUE TITLE
[Feature Request] Implementation of auto update 

### ISSUE THREAD

**Issue by siavash79** [kdrag0n/safetynet-fix#151]
Hi

Magisk 24 added support for in-app update instead of magisk-repo, using update JSON, which auto checks for latest module update online.

It will be nice to implement it in the module, so that users don't manually check GitHub every now and then.

**Comment by ipdev99** [comment]
All ready in progress. :upside_down_face: 
PR https://github.com/kdrag0n/safetynet-fix/pull/140

:cowboy_hat_face:

**Comment by kdrag0n** [comment]
Added by #140

**Comment by skobkin** [comment]
Will there be a release with this code merged anytime soon?
