### ISSUE TITLE
Cts profile fails in havoc os 3.12 gsi

### ISSUE THREAD

**Issue by Relected** [kdrag0n/safetynet-fix#152]
I have the zygisk module installed and running but the only thing not passing is CTS

Magsik hide prop doesn't work either

**Comment by restokroka** [comment]
I have galaxy s9+ and cts profile fails too. zygisk + denylist doesnt work for me, even tried shamiko and props fingerprint change.

**Comment by Relected** [comment]
@restokroka Magisk hide prop needs to be updated to support zygisk or it will not work

**Comment by restokroka** [comment]
> @restokroka Magisk hide prop needs to be updated to support zygisk or it will not work

I have latest version of everything. I tried different fingerprints, not working. Only CTS is not passing.

**Comment by Relected** [comment]
@restokroka same, but Magisk denylistade my life a bit more bearable, I was able to use my banking app with it (works with microg too)

**Comment by Lorramaeloveharry** [comment]
Same here any idea to Fix this issue??
I tried everything. I really need help
Right now

**Comment by Relected** [comment]
@LorainLacosta apparently the issue cannot be fixed for i have installed a custom gsi rom which permanently fails CTS check, my device is detected as hi6250 which is not a certified device in safetynet 

this issue persists between all gsi roms i have tried, all of them, so its not a havoc os specific issue

**Comment by kdrag0n** [comment]
You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481

**Comment by Relected** [comment]
@kdrag0n apparently after checking with momo, CTS fails because it detects that the bootloader is unlocked, even if the module is enabled
