### ISSUE TITLE
No SIM CARD - OP 9 Pro 

### ISSUE THREAD

**Issue by dramcio** [kdrag0n/safetynet-fix#154]
Hello
I have One Plus 9 Pro version (C44) BA

I've installed root & magisk 24.1.
Turn on deny list & zygisk. 
Now I'm installing safetynet-fix module. 

After this step I'm getting issue "NO SIM CARD".

I could not open settings -> mobile network (after click, no reaction)
I could not call anybody.

Turning off the module, does not help. 
Wifi & Bluetooth work fine.

After installing again whole rom, my SMS get lost but sim works.

Edit:

I see logs from adb

`Failed to open database '/data/user_de/0/com.android.providers.telephony/databases/carrierIdentification.db'.
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user_de/0/com.android.providers.telephony/databases/carrierIdentification.db': Directory /data/user_de/0/com.android.providers.telephony/databases doesn't exist`

**Comment by Geofferey** [comment]
Try clearing app data for telephony based applications? Remove the sim as well and reinsert after app data wipe?

**Comment by kdrag0n** [comment]
Please get logs from a computer by running `adb logcat > issue.log` and uploading the file here.

Personal/private information may be present in the log, so feel free to redact it or PM it (referencing this issue) on Telegram.

**Comment by kdrag0n** [comment]
Closing due to missing info.
