### ISSUE TITLE
Safety Net Check Failed on ONEPLUS 6

### ISSUE THREAD

**Issue by Lihsrah** [kdrag0n/safetynet-fix#155]

**Comment by Lihsrah** [comment]
![Screenshot_20220210-112012.png](https://user-images.githubusercontent.com/73928189/153346362-49f60f60-c8f7-4fff-a98a-946f9d3b4aa4.png)![Screenshot_20220210-112028.png](https://user-images.githubusercontent.com/73928189/153346368-efa2281c-6dc5-45cb-8d5a-02408197f34e.png)

**Comment by HuskyDG** [comment]
> ![Screenshot_20220210-112012.png](https://user-images.githubusercontent.com/73928189/153346362-49f60f60-c8f7-4fff-a98a-946f9d3b4aa4.png)![Screenshot_20220210-112028.png](https://user-images.githubusercontent.com/73928189/153346368-efa2281c-6dc5-45cb-8d5a-02408197f34e.png)

Restore back to stock rom :>

**Comment by Lihsrah** [comment]
![Screenshot_20220219-105838.png](https://user-images.githubusercontent.com/73928189/154787694-01cbf6d4-5fcd-41f0-a331-808a35fcbd73.png)

**Comment by Lihsrah** [comment]
It used to paas before recent magisk update

**Comment by Lihsrah** [comment]
> > ![Screenshot_20220210-112012.png](https://user-images.githubusercontent.com/73928189/153346362-49f60f60-c8f7-4fff-a98a-946f9d3b4aa4.png)![Screenshot_20220210-112028.png](https://user-images.githubusercontent.com/73928189/153346368-efa2281c-6dc5-45cb-8d5a-02408197f34e.png)
> 
> Look like you had added gms to denylist, please remove it from DenyList to allow usnf to hook into gms
> If this doesn't help, Restore back to stock rom :>

It used to paas before recent magisk update
![Screenshot_20220219-105838.png](https://user-images.githubusercontent.com/73928189/154787770-46f5f350-e793-457f-959a-25327f16ea4d.png)

**Comment by HuskyDG** [comment]
> > > ![Screenshot_20220210-112012.png](https://user-images.githubusercontent.com/73928189/153346362-49f60f60-c8f7-4fff-a98a-946f9d3b4aa4.png)![Screenshot_20220210-112028.png](https://user-images.githubusercontent.com/73928189/153346368-efa2281c-6dc5-45cb-8d5a-02408197f34e.png)
> > 
> > 
> > Look like you had added gms to denylist, please remove it from DenyList to allow usnf to hook into gms
> > If this doesn't help, Restore back to stock rom :>
> 
> It used to paas before recent magisk update ![Screenshot_20220219-105838.png](https://user-images.githubusercontent.com/73928189/154787770-46f5f350-e793-457f-959a-25327f16ea4d.png)

Restore to stock rom

**Comment by HuskyDG** [comment]
> > > > > ![Screenshot_20220210-112012.png](https://user-images.githubusercontent.com/73928189/153346362-49f60f60-c8f7-4fff-a98a-946f9d3b4aa4.png)![Screenshot_20220210-112028.png](https://user-images.githubusercontent.com/73928189/153346368-efa2281c-6dc5-45cb-8d5a-02408197f34e.png)
> > > > 
> > > > 
> > > > Look like you had added gms to denylist, please remove it from DenyList to allow usnf to hook into gms
> > > > If this doesn't help, Restore back to stock rom :>
> > > 
> > > 
> > > It used to paas before recent magisk update ![Screenshot_20220219-105838.png](https://user-images.githubusercontent.com/73928189/154787770-46f5f350-e793-457f-959a-25327f16ea4d.png)
> > 
> > 
> > Restore to stock rom
> 
> Thanks for the suggestion mate but i dont like stock rom because nethunter won't work there :')

So close this issues since it was invalid :>

**Comment by kdrag0n** [comment]
You need to try making more changes, which are out-of-scope for Universal SafetyNet Fix: https://t.me/proton_projects/40481
