### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by XspeedPL** [kdrag0n/safetynet-fix#156]
I have a device stuck on Android 7.1 (LG W200E), but I was pleased to see that after removing the SDK restriction from customize script and flashing it just works and I can use Google Pay again.

So my question is, why is Android 8 listed as the minimum supported version?

Android 7.1
Magisk Alpha 24102 by vvb2060
SafetyNet Fix v2.2.1

**Comment by XspeedPL** [comment]
Why should I use MHPC if this works for me? lol

Nowadays this module does way more than just forcing basic attestation.

**Comment by MlgmXyysd** [comment]
Android 7.1 does not support hardware attestation. You can remove everything except props.
BTW, do NOT use Magisk Alpha, use the official Magisk instead.
