### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by carldw** [kdrag0n/safetynet-fix#157]
After installing the module the fingerprint sensor stops working on all Bank apps while I'm using a bypass that allows them to work

**Comment by ToLive** [comment]
Oneplus 8 pro, Oxygen 12 open beta 1. Also fingerprint stopped working. Any advice to fix this?

**Comment by carldw** [comment]
I had to install hardware off the s9+ and it fixed it

**Comment by ruszok** [comment]
> I had to install hardware off the s9+ and it fixed it

What do you mean? What do you exactly install?

**Comment by ToLive** [comment]
I manage to fix fingerprint with additional module https://github.com/wuxianlin/ColorOSMagisk

**Comment by ToLive** [comment]
> It works for you? I have this modules (img) and fingerprint reader doesn't work.

Yes. I also have 2 more modules, but they should not affect fp. 
https://github.com/stylemessiah/SQLite3UniversalBinaries
https://github.com/stylemessiah/GPay-SQLite-Fix

**Comment by ruszok** [comment]
> > It works for you? I have this modules (img) and fingerprint reader doesn't work.
> 
> Yes. I also have 2 more modules, but they should not affect fp. https://github.com/stylemessiah/SQLite3UniversalBinaries https://github.com/stylemessiah/GPay-SQLite-Fix

![Screenshot_2022-03-01-19-53-01-12_62c0b7ebb4efdb032e4a9bc93a882365](https://user-images.githubusercontent.com/68990273/156230900-7dbe4d90-61c8-4112-8089-62f6b7de7d1c.jpg)
I don't know why it doesn't work... I uninstall/reinstall magisk, all modules... And nothing.
I have 8T EU KB2003, beta 1 OOS12 is NA KB2005 - maybe that is the reason...

**Comment by ToLive** [comment]
> I don't know why it doesn't work... I uninstall/reinstall magisk, all modules... And nothing. I have 8T EU KB2003, beta 1 OOS12 is NA KB2005 - maybe that is the reason...

Maybe install order also matters? In my log "coloros-magisk" starts after "safetynet-fix" (876 section in your log)

**Comment by ruszok** [comment]
Could be the reason (I see that also). But I installed first safetynetfix and then ColorOS fix.

**Comment by iconicecho** [comment]
> Could be the reason (I see that also). But I installed first safetynetfix and then ColorOS fix. You have zygisk and deny list?
> 
> Ok. You have right. Install order... I reinstall all once again in right order with reboots... And it works finally! Thanks! ![Screenshot_2022-03-01-21-24-49-96_62c0b7ebb4efdb032e4a9bc93a882365](https://user-images.githubusercontent.com/68990273/156243438-d7652a17-e9b6-4e06-b4c2-38ec74cbd393.jpg)

How did you change the order so that safetynet was loaded first?

**Comment by ruszok** [comment]
Uninstall all magisk modules (or maybe this two will be also ok).
Reboot.
Install safetynetfix.
Reboot.
Install ColorOS Magis Module.
Reboot.
Install all other modules.
Reboot.

**Comment by osm0sis** [comment]
Can someone test by uninstalling the ColorOSMagisk module and adding my PR's prop changes to USNF?

**Comment by ToLive** [comment]
> Can someone test by uninstalling the ColorOSMagisk module and adding my PR's prop changes to their USNF module on-device?

Tested right now and everything is working. My steps:
1. ColorOSMagisk was uninstalled
2. Changed 2 files in /data/adb/modules according to PR
3. Reboot
4. Safetynet check passed, fp working

Thank you!

**Comment by ruszok** [comment]
Wow. Thanks.
So will be an update of SafetyNetFix or what?

**Comment by ToLive** [comment]
> Wow. Thanks.
> So will be an update of SafetyNetFix or what?

Will be in the next update after merge of PR. For now, you can still use 2 modules. After a new version, ColorOsMagisk can be uninstalled.

**Comment by dikeckaan** [comment]
I am on Oneplus 8T OxygenOS 12 C.11 IND Fod working but cts profile fail.

Tried change [this](https://github.com/kdrag0n/safetynet-fix/pull/164)

logs is here

[magisk_log_2022-03-20T13_56_48.log](https://github.com/kdrag0n/safetynet-fix/files/8311079/magisk_log_2022-03-20T13_56_48.log)

I appreciate your hard work. Thanks @kdrag0n

**Comment by ToLive** [comment]
> I am on Oneplus 8T OxygenOS 12 C.11 IND Fod working but cts profile fail.
> 
> Tried change [this](https://github.com/kdrag0n/safetynet-fix/pull/164)
> 
> logs is here
> 
> [magisk_log_2022-03-20T13_56_48.log](https://github.com/kdrag0n/safetynet-fix/files/8311079/magisk_log_2022-03-20T13_56_48.log)
> 
> I appreciate your hard work. Thanks @kdrag0n

Show content of this files:
![Screenshot_2022-03-21-09-33-12-68_e66e28f718147b6e7216efe19a1092f5](https://user-images.githubusercontent.com/2019736/159220198-b71b660c-85b0-4aeb-93e7-7135c08b3c21.jpg)

**Comment by frnode** [comment]
@carldw @ToLive @ruszok @iconicecho @dikeckaan
Look at my answer here: https://github.com/kdrag0n/safetynet-fix/issues/177#issuecomment-1129165825?plain=1
