### ISSUE TITLE
Set sys.oem_unlock_allowed to 0

### ISSUE THREAD

**Issue by josesilveiraa** [kdrag0n/safetynet-fix#160]
I think it's a good idea because apps can tell if the toggle is on and block the access, would be a good addition.

**Comment by Jon8RFC** [comment]
Is something like this a potential issue:
https://forum.xda-developers.com/t/enable-oem-unlock-in-developer-options.3369084/#post-77005999

**Comment by josesilveiraa** [comment]
> Is something like this a potential issue: https://forum.xda-developers.com/t/enable-oem-unlock-in-developer-options.3369084/#post-77005999

Makes sense

**Comment by VladWinner** [comment]
I highly recommend not changing this value.
