### ISSUE TITLE
autoupdate missing?

### ISSUE THREAD

**Issue by Azraelle** [kdrag0n/safetynet-fix#161]
I don't see the grey 'update' button in the module list. And it should be there.

**Comment by VladWinner** [comment]
> And it should be there.

It can't be there because it's not implemented. The described functionality appeared in Magisk later than release date of latest safetynet-fix build.

**Comment by HuskyDG** [comment]
The issue is invalid and should be closed

**Comment by kdrag0n** [comment]
This has already been added for the next release.
