### ISSUE TITLE
Dissables fingerprint sensor.

### ISSUE THREAD

**Issue by waddras** [kdrag0n/safetynet-fix#168]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Device info**
Device model:
Android version:
ROM name/version:

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by JakobLichterfeld** [comment]
Seems like same issue as [#173](https://github.com/kdrag0n/safetynet-fix/issues/173)

**Comment by frnode** [comment]
@waddras 
Look at my answer here: https://github.com/kdrag0n/safetynet-fix/issues/177#issuecomment-1129165825?plain=1

**Comment by kdrag0n** [comment]
Fixed in [v2.3.1](https://github.com/kdrag0n/safetynet-fix/releases/tag/v2.3.1).
