### ISSUE TITLE
Publish to magisk

### ISSUE THREAD

**Issue by soredake** [kdrag0n/safetynet-fix#17]
Would be nice to have this on magisk repo https://github.com/Magisk-Modules-Repo/submission

**Comment by kdrag0n** [comment]
My response on XDA as of January 14:

> The official module repository appears to have been inactive for a few months, so that's unlikely to happen in the near future.

The situation does not appear to have changed. See https://github.com/Magisk-Modules-Repo/submission/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed for context.
