### ISSUE TITLE
CTS profile failed, unlocked bootloader still detected 

### ISSUE THREAD

**Issue by Relected** [kdrag0n/safetynet-fix#170]
**Describe the bug**
This module doesn't hide bootloader status in my custom ROM 

**Expected behavior**
Passing CTS in safetynet

**Screenshots**
![Screenshot_20220313-121558_YASNAC](https://user-images.githubusercontent.com/61807003/158624576-37637dfc-fb60-46dd-8dfb-f404447bea36.png)

![Screenshot_20220316-171436_Trebuchet](https://user-images.githubusercontent.com/61807003/158624613-9d666def-3553-4574-801b-50ee028e80fd.png)

![Screenshot_20220316-171344_Trebuchet](https://user-images.githubusercontent.com/61807003/158624653-0d211ada-0f44-44c3-be22-cc32509f5849.png)

**Device info**
Device model: Huawei Fla-lx1
Android version:11
ROM name/version: CAOS11

**Checklist**
- [x] All information is present
- [ ] Logs are attached
- [x] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by Displax** [comment]
Show your current config in MHPC and selinux state.

**Comment by Displax** [comment]
> > Use MHPC https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf and configure valid build.fingerprint
> 
> I already did that, did you read my issue all the way?

No, you didn't. Your fingerprint still unchanged.

![158624653-0d211ada-0f44-44c3-be22-cc32509f5849](https://user-images.githubusercontent.com/16293419/158654941-6862fff8-4d3f-4fa3-8288-7e3773453d83.png)

**Comment by Relected** [comment]
@Displax se Linux enforcing, also magiskhide props did nothing to help, so idk

**Comment by Displax** [comment]
Your problem is not about bootloader status not hidden for MOMO (it uses HARDWARE method).
You need to change fingerprint, if MHPC don't working for you - do it by another way (and send correct bugreport to MHPC issues section).

**Comment by peepshow-21** [comment]
I'm using Lineage 18.1 (nightly) on a OP 9 (lemonade)
Magisk 24.3 with 2.2.1 module

I'm getting CTS Profile match fail too.

Can I post anything useful here to help figure out why?

**Comment by pndwal** [comment]
> @Displax se Linux enforcing, also magiskhide props did nothing to help, so idk

Did you select fingerprint from list when configuring MHPC w/ a terminal emulator app?... Or it will do nothing of course... This is always needed w/ official LOS for example, but unofficial and other custom ROMs may spoof certified (fingerprint) themselves... @Displax knows his stuff...

SafetyNet passes for me on RN8T, but Momo always detects unlocked bootloader on MIUI (unless we fiddle with mediatek SECCFG or snapdragon DEVINFO partitions)... Not detected on many devices however...

**Comment by pndwal** [comment]
> @Displax se Linux enforcing, also magiskhide props did nothing to help, so idk

Did you select fingerprint from list when configuring MHPC w/ a terminal emulator app?... Or it will do nothing of course... This is always needed w/ official LOS for example, but unofficial and other custom ROMs may spoof certified (fingerprint) themselves... @Displax knows his stuff...

SafetyNet passes for me on RN8T, but Momo always detects unlocked bootloader on MIUI (unless we fiddle with mediatek SECCFG or snapdragon DEVINFO partitions)... Not detected on many devices however...

**Comment by pndwal** [comment]
> I'm using Lineage 18.1 (nightly) on a OP 9 (lemonade) Magisk 24.3 with 2.2.1 module
> 
> I'm getting CTS Profile match fail too.
> 
> Can I post anything useful here to help figure out why?

@kdrag0n covers need for MHPC in USNF GitHub main page... Covered in comments above also....

**Comment by Relected** [comment]
@pndwal yes I did select a fingerprint, still nothing.

**Comment by AlexKusnezov** [comment]
for me selecting fingerprint (OnePlus 6t Android 11) although I'm on LOS 19.1 did the trick
