### ISSUE TITLE
CTS fails

### ISSUE THREAD

**Issue by mercertom** [kdrag0n/safetynet-fix#171]
Tried several pixel fingerprints -- does it have to be an a12 fingerprint for a12 ROM?

G Play Services keeps unchecking itself on reboot in Magisk deny list. That seems crucial.

No matter which fingerprint I configure, and I've tried several, all pixels, mostly a12, I'm able to force basic, basic passes, and CTS profile match fails.

Pixel Experience a12, joan

**Comment by kamild1996** [comment]
Looks like SafetyNet was updated, I'm also failing CTS even though I was definitely passing it before.

**Comment by eBug** [comment]
Same problem here with LineageOS 18.1 on Pixel XL

**Comment by kuukks** [comment]
I've got the same problem too.
I'm on cr droid 8.2

**Comment by Nemisor** [comment]
I believe it's caused by the new Remote Key Provisioning they added recently, failing for me as well.

**Comment by bigjoncoop** [comment]
Same Issue. Just started failing Safety Net Checks. 

Unlocked Bootloader / Running Android 11 / Safety Net Fix  v2.2.1 (Zygisk) / Magisk Ver. 24.3 w/ Zygisk / Oneplus Nord N10 5G / OxygenOS 11.0.2.BE86AA

**Comment by mercertom** [comment]
Any idea when CTS can succeed?

**Comment by mattg66** [comment]
Same issue here, G Play Services keeps unchecking itself on reboot in Magisk deny list.
Lineage OS 19.1 OP6T

**Comment by mattg66** [comment]
Update, I fixed the issue using https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf and setting the props of my device to its model.

**Comment by mercertom** [comment]
I hadn't noticed, but G Play Services unchecks itself on mine.

How can setting props to itself fix the issue? That makes no sense. Every certified fingerprint should work or none. I tried this, and it makes no difference what fingerprint I use.

**Comment by alucryd** [comment]
Well, @mattg66 did work here, go figure. Thanks for the tip!
