### ISSUE TITLE
 under-display fingerprint sensor does not work on Oneplus KB2000 devices 

### ISSUE THREAD

**Issue by jiang-yuan** [kdrag0n/safetynet-fix#179]
**Describe the bug**
 under-display fingerprint sensor does not work 

**To reproduce**
1. open gpay
2. press finger
3. no response

**Expected behavior**
unlock by fingerprint

**Screenshots**

**Device info**
Device model:Oneplus KB2000
Android version: 12
ROM name/version: Coloros 12.1

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [x] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by Doggie52** [comment]
The changes in https://github.com/kdrag0n/safetynet-fix/commit/55f892fb8855a7867a186970e0bfc31e665ab183 fix this issue.

You can make these changes yourself in the latest release (v2.2.1) - just download the release zip and edit the files according to that commit, then save the zip and finally flash it.

Until a new release is made that incorporates these changes, this is the only way to do it.

**Comment by Doggie52** [comment]
[safetynet-fix-v2.2.1-patched.zip](https://github.com/kdrag0n/safetynet-fix/files/8622069/safetynet-fix-v2.2.1-patched.zip)

Here's the one I patched. If you don't trust me, you are welcome to follow the steps I outlined.

**Comment by jiang-yuan** [comment]
It's ok, but why the author does not release a new version since there is already a fix commit in Mar.

**Comment by frnode** [comment]
@jiang-yuan @Doggie52
Look at my answer here: https://github.com/kdrag0n/safetynet-fix/issues/177#issuecomment-1129165825?plain=1

**Comment by Doggie52** [comment]
Not sure what your change fixes in addition to what's fixed in https://github.com/kdrag0n/safetynet-fix/commit/55f892fb8855a7867a186970e0bfc31e665ab183? Applying just that change is enough to get my fingerprint working.

**Comment by frnode** [comment]
@Doggie52 The change https://github.com/kdrag0n/safetynet-fix/commit/55f892fb8855a7867a186970e0bfc31e665ab183, does fix the fingerprint, but if you check SafetyNet it doesn't pass as valid.
At first I also just recompiled the code thinking it was good, but the safetynet is not good...

**Comment by Doggie52** [comment]
It passes fine for me. I didn't recompile the code, I simply edited those lines in the existing release zip.

**Comment by frnode** [comment]
@Doggie52 That's why then, you have the old version which doesn't include the latest changes from the repo and you applied the changes directly on the 2.2.1 version. So there are not necessarily big differences between your change and my version, but many people are facing the problem and there is no solution out of the box, despite reporting the problem for months... That's why I created the fork to make it a compiled version and people can see the source.

**Comment by Doggie52** [comment]
Ah, yes, makes sense. Thanks for explaining!

**Comment by adwil13** [comment]
For complete solution that fixes both Google Play Certification, CTS profile and Google Pay please see: https://github.com/kdrag0n/safetynet-fix/issues/188#issuecomment-1147295375

**Comment by jiang-yuan** [comment]
> For complete solution that fixes both Google Play Certification, CTS profile and Google Pay please see: [#188 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/188#issuecomment-1147295375)

I am wondering if there are simpler way...

**Comment by actuallymentor** [comment]
After upgrading to android 12 the fingerprint stopped working reliably on Oneplus 7t. Disabling the mobile and rebooting restores desired behavior.
