### ISSUE TITLE
 Huawei p10 pin lock

### ISSUE THREAD

**Issue by cichy63** [kdrag0n/safetynet-fix#18]
I noticed after installation of v1.1.1 that it  works but after while - some hours, it breaks somehow the menu when i enter pin unlock on my phone. It,s not SIM pin but one i need to use for every phone restart. Im entering my pin but the service restarts and ask my again for pin. Unfortunatelly factory reset was my only option in this case. I run lineage 16  by OpenKirin group. Any option for resolving that?

**Comment by NULL0B** [comment]
Check this. There is a test version, That should fix it
https://github.com/kdrag0n/safetynet-fix/pull/13

**Comment by cichy63** [comment]
Hi @NULL0B,

just installed this one. Phone rebooted ok, and looks that it did not break anything (yet) but cts is not passed with it....

**Comment by kdrag0n** [comment]
This is the same underlying issue as #13.
