### ISSUE TITLE
I have a curious problem.

### ISSUE THREAD

**Issue by JesusMaxim** [kdrag0n/safetynet-fix#180]
When installing the module if it fulfills its function, I approve the satefynet, but it blocks the bootloader, when I remove it reopens

-Android 10/MIUI 12.0.21
-Redmi 9C 
-Magisk 24.3
-zygisk with denylist

the rest of the information is irrelevant because the problem only happens when I install the module.

**Comment by MikuDroid** [comment]
Wdym "blocks bootloader"? The one you saw on developer options? It supposed to be like that after you install the module, you don't need to worry.

**Comment by JesusMaxim** [comment]
>  "blocks bootloader"? The one you saw on developer options? It supposed to be like that after you install the module, you don't need to worry.

I say that because it also affected the padlock that appears when the system starts, I don't know if this is normal

**Comment by MikuDroid** [comment]
as long you still able to boot modified stuff (in this case it's the boot image that patched with magisk) your bootloader is still unlocked.

**Comment by JesusMaxim** [comment]
> 

Thanks for your help, and sorry for the inconvenience, I am new to the kernel and how Magisk works inside.

**Comment by JesusMaxim** [comment]
> as long you still able to boot modified stuff (in this case it's the boot image that patched with magisk) your bootloader is still unlocked.

Thanks for your help, and sorry for the inconvenience, I am new to the kernel and how Magisk works inside.
