### ISSUE TITLE
Deny list clear Google Play Services

### ISSUE THREAD

**Issue by mywalkb** [kdrag0n/safetynet-fix#186]
**Describe the bug**
I have Magisk canary 24312 (tested also on 24300) and module 2.2.1 when boot the device with module enabled all process of Google Play Services disappear from deny list.
Module should use only unstable process so all other process can be added to deny list. After the boot if I add all process except unstable, the module work correctly pass safetynet with basic and not hardware.

**To reproduce**
1. Put in denylist of magisk one or more process of Google Play Service
2. Reboot
3. Check denylist all process Google Play Service are missing

**Expected behavior**
All process of Google Play Service must remain in denylist and not removed. If I disable module safetynet-fix after reboot the process remain.

**Screenshots**
No

**Device info**
Device model: LG G5
Android version: 11
ROM name/version: LineageOS 18.1

**Logs**

**Additional context**
No

**Checklist**
- [X] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by Denbrea** [comment]
I can confirm the bug on my phone

Device info
Device model: OnePlus 7T Pro
Android version: 11
ROM name/version: Oxygen OS 11.0.6

**Comment by Displax** [comment]
It's not a bug. Expected behaviour.

**Comment by mywalkb** [comment]
I analyzed better the code, so I explain also for novice as me.
When the GMS processes are loaded the module unmount magisk for the process with
`api->setOption(zygisk::FORCE_DENYLIST_UNMOUNT)`
So GMS processes can't detect magisk and the module can continue to inject classes.dex in unstable process.
