### ISSUE TITLE
GMS setting crash

### ISSUE THREAD

**Issue by STTecCEO** [kdrag0n/safetynet-fix#192]
**Describe the bug**
This module makes my Google account setting(com.google.android.gms) crash，but other Google function and module works fine.

**To reproduce**
1. Go to 'Setting'
2. Click on 'Google'
3. Crash then flashback to setting
OR
1.Go to 'Google play store'
2. Tap 'Manage your Google Account'
3. Crash then flashback to play store

**Expected behavior**
fix it 

**Screenshots**
![Video_20220613_042504_255](https://user-images.githubusercontent.com/35169436/173311703-d59fae59-88e9-4316-982d-df5803de239a.gif)

**Device info**
Device model:SONY XPERIA1 Ⅲ
Android version:12
ROM name/version:sony stock

**Logs**
[issue.log](https://github.com/kdrag0n/safetynet-fix/files/8889379/issue.log)

**Checklist**
- [ √] All information is present
- [ √] Logs are attached
- [√ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by HuskyDG** [comment]
Do you use any module else?

**Comment by STTecCEO** [comment]
![Screenshot_20220614-085222](https://user-images.githubusercontent.com/35169436/173470866-cbcb78af-2727-4610-ae42-e6f00cdee3c3.png)

**Comment by HuskyDG** [comment]
Hi @STTecCEO
Sorry for letting you wait, you can try disabling all modules and restart. Maybe atleast one module cause problem.

**Comment by STTecCEO** [comment]
found the reason,  caused by the font module, it's strangely why they are conflict....

**Comment by HuskyDG** [comment]
> found the reason, caused by the font module, it's strangely why they are conflict....

Strange behavior of Android 12.
Duplicated of https://github.com/Androidacy/FontManager-Module/issues/8, https://github.com/kdrag0n/safetynet-fix/issues/172

**Comment by HuskyDG** [comment]
I think this issue should be closed
