### ISSUE TITLE
google password manager not working and other google play services 

### ISSUE THREAD

**Issue by Lemuel2631** [kdrag0n/safetynet-fix#193]
**Describe the bug**
After installing universal saftynet fix i can't use google password autofill, gmail notification not working and "hey Google" google assistant not working 

**To reproduce**
1. Go to 'SETTINGS'
2. Click on 'PASSWORD'
3. Click on 'manage password'
4. See error"Unavailable because the device is offline"

**Expected behavior**
FIX

**Screenshots**

**Device info**
Device model:RMX2202 / REALME GT
Android version:12
ROM name/version:REALME UI 3.0

**Logs**
https://drive.google.com/file/d/1o-mi1ENt8s7TOes7L2rM94buvhKGKe4T/view?usp=drivesdk

**Additional context**

**Checklist**
- [ ✓] All information is present
- [ ✓] Logs are attached
- [ X ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

https://user-images.githubusercontent.com/108019294/175104667-a1dc9f1d-6a50-480f-9501-7d31c4700d61.mp4

![Screenshot_2022-06-23-01-47-03-64_f3368379c7c9751b62ecbc13b25c398a](https://user-images.githubusercontent.com/108019294/175104677-bcc438ac-7363-404b-ab36-ad445180d785.jpg)
![Screenshot_2022-06-23-01-47-07-99_f3368379c7c9751b62ecbc13b25c398a](https://user-images.githubusercontent.com/108019294/175104698-ac989fa4-8c5c-46b6-9057-f004977b0606.jpg)
![Screenshot_2022-06-23-01-47-29-33_f3368379c7c9751b62ecbc13b25c398a](https://user-images.githubusercontent.com/108019294/175104700-ba5482cd-b544-4789-ba50-79d0e9746bd1.jpg)
![Screenshot_2022-06-23-01-03-47-64_9492aa3750dca76abb7c25b39a5f1e8e](https://user-images.githubusercontent.com/108019294/175104706-4f25d0d4-ff87-4c09-a70b-7ef4eb859a56.jpg)
![Screenshot_2022-06-23-01-00-59-12_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/108019294/175104713-40fb4368-9d77-4bc6-86c2-b6fafebb8cbe.jpg)

**Comment by HuskyDG** [comment]
Try this fix, i have moved all props to boot completed stage

**Comment by Lemuel2631** [comment]
After i uninstalled the old safetyFix and apply the one you game me the google play services works but the cts profile match fail

I tried to install the old zip then install the new safetyfix the cts profile PASS but the google service won't work.

**Comment by HuskyDG** [comment]
> After i uninstalled the old safetyFix and apply the one you game me the google play services works but the cts profile match fail
> 
> I tried to install the old zip then install the new safetyfix the cts profile PASS but the google service won't work.

Try kill the Google Services process with these commans:
```
killall com.google.android.gms
killall com.android.vending
```
And run the check again

**Comment by HuskyDG** [comment]
It seems early props appeared to break some device functions on ROM with weird behaviors. But late props might not effective.

**Comment by Lemuel2631** [comment]
I uninstalled the old safetyFix and apply the one gave me, the google service work but the cst profile match FAIL.

I tried to install the old safetyFix and apply the new safetyfix that you gave, the cst profile PASS but the google service won't work.

**Comment by Lemuel2631** [comment]
![Screenshot_2022-06-24-15-42-54-24_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/108019294/175488528-b8ad4d44-27f2-43aa-aba3-9d0cf7c061fe.jpg)

**Comment by HuskyDG** [comment]
@Lemuel2631 why not execute in root shell?

**Comment by Lemuel2631** [comment]
How?

**Comment by Lemuel2631** [comment]
![Uploading Screenshot_2022-06-24-17-13-54-30_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Lemuel2631** [comment]
![Screenshot_2022-06-24-17-13-54-30_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/108019294/175504580-3f8e1035-ef7a-48dd-adf2-afd48223a1c0.jpg)

**Comment by Lemuel2631** [comment]
Google play services not working.
