### ISSUE TITLE
Oneplus8pro since 1 week CTS fail - Google Pay 

### ISSUE THREAD

**Issue by mxcxpx** [kdrag0n/safetynet-fix#194]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Device info**
Device model:
Android version:
ROM name/version:

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by kdrag0n** [comment]
Duplicate of #188
