### ISSUE TITLE
OnePlus Nord 

### ISSUE THREAD

**Issue by Skia13** [kdrag0n/safetynet-fix#196]
2.3.1 fingerprint not working. Only works when I disable the module

**Comment by HuskyDG** [comment]
Try this

[safetynet-fix-v2.3.1.zip](https://github.com/kdrag0n/safetynet-fix/files/9024553/safetynet-fix-v2.3.1.zip)

**Comment by HuskyDG** [comment]
@Skia13 are you there?

**Comment by boozelightbeer** [comment]
+1. the bug still exists on v2.3.1. works when the module isn't enabled. multiple clean flashes done. if the first thing i install is this module, fingerprint stops working immediately, so I'm sure it is because of this module. 
p.s. thanks for maintaining this module. helps me big time. :)

**Comment by andilem** [comment]
Please check the attached file. It is different from the original 2.3.1 file. But it should really be renamed to v2.3.1.1!

**Comment by HuskyDG** [comment]
> Please check the attached file. It is different from the original 2.3.1 file. But it should really be renamed to v2.3.1.1!

The author of this issue does not response so I can't verify

**Comment by makerr00** [comment]
The atached modified file of 2.3.1 works on op7t oos12 openbeta1, previous versions 2.3.1 and below didn't work,but the modified one works

**Comment by boozelightbeer** [comment]
> > Please check the attached file. It is different from the original 2.3.1 file. But it should really be renamed to v2.3.1.1!
> 
> The author of this issue does not response so I can't verify

i tried the v2.3.1.1 zip for two days, fp started working normally for a day and on the second the problem started again. im not sure what made the change but uninstalling the module makes fp work again instantly. ill try reinstalling magisk and module. 
i have the same phone and most likely the same OS build as the author.

**Comment by HuskyDG** [comment]
> > > Please check the attached file. It is different from the original 2.3.1 file. But it should really be renamed to v2.3.1.1!
> > 
> > 
> > The author of this issue does not response so I can't verify
> 
> i tried the v2.3.1.1 zip for two days, fp started working normally for a day and on the second the problem started again. im not sure what made the change but uninstalling the module makes fp work again instantly. ill try reinstalling magisk and module. i have the same phone and most likely the same OS build as the author.

I guess the system could think the bootloader was still locked and then used hardware attestation which were being disabled when unlocking bootloader on OnePlus devices

**Comment by marcelhdhd** [comment]
@HuskyDG Thank you, that worked for now. 👍🏻 

Will monitor if @boozelightbeer 's claim of the fingerprint issue starting again after a day or so will happen too for me.

Write me if you need additional help with logs or so

**Comment by IBlackfireI** [comment]
I tested the attached file with my op nord and the fingerprint sensor works again

**Comment by iAmMrinal0** [comment]
Recently updated my OP7T to OOS12 via official update to: HD1901_11_F.17 and had root Magisk. Fingerprint wasn't working so updated safetynet-fix to 2.3.1 from releases, which did not work. The attached file in the comments worked for me. 👏

**Comment by fzechert** [comment]
I can also confirm that the modified file works on my OnePlus 7T with the operating system `OxygenOS 12.1 | Android 12 | HD1903_11_F.17` 

Thank you very much @HuskyDG 

This enables the finger print sensor and, at the same time allows me to use Google Pay without problems. <3
