### ISSUE TITLE
Bootloop on samsung note 20 Ultra

### ISSUE THREAD

**Issue by joodallah** [kdrag0n/safetynet-fix#2]
The phone reboots continuously. Sometimes the phone keeps on and I check Safetynet and it passes the test. But if I restart it will bring back the keep restarting issue again.

**Comment by kdrag0n** [comment]
As per the README:

> **Heavy OEM skins are not officially supported**, but they may work depending on your luck and the particular ROM in question. Please do not report problems on such ROMs.

Samsung One UI is one such ROM.
