### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by zeuLL** [kdrag0n/safetynet-fix#201]
Google pay not work with Safetynet in Oneplus 8t KB2500_11_c.21 ? 

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Device info**
Device model:
Android version:
ROM name/version:

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by HuskyDG** [comment]
@zeuLL Come back here and correct your issue

**Comment by Snuupy** [comment]
+1 https://www.reddit.com/r/Magisk/comments/w3n7ln/help_google_pay_no_longer_fooled_by_magisk_hide/

**Comment by HuskyDG** [comment]
Btw, Zygisk is not for hiding anymore and there are already apps detect zygisk.
