### ISSUE TITLE
Please make 'Universal deviceIntegrity Fix for PI API' ...

### ISSUE THREAD

**Issue by pndwal** [kdrag0n/safetynet-fix#204]
Fixes to expand 'Universal SafetyNet Fix' to become a 'Universal device Integrity Fix for PI API' are needed.

The SafetyNet Attestation API is deprecated and has been replaced by the Play Integrity API.
https://developer.android.com/training/safetynet/deprecation-timeline

New Play Integrity API is rolling out from June 2022, and evidently Google Play Store and Google Pay/Wallet are already using its verdict.

June 2023 is the Migration Deadline for app developers. This will also allow their older app versions to continue working with SafetyNet API for a limited time.

June 2024 is the End of life for SafetyNet API; its attestation will no longer work for any app version, and apps will receive an error.

The new Integrity API has more strict requirements for passing attestation, and seems to require extra prop mismatches to trigger hardware based verdict enforcement bypassing in Android 11+ particularly.

Currently (evidently due to this), device security issues are detected by
1) Google Pay/Wallet, which may state "You can't pay contactless with this device...(Your phone doesn't meet software standards)" on updating or attempting to add a card despite in-app Contactless setup stating "You're ready to pay contactless with your phone (Your phone meets security requirements)", and
2) Google Play Store, which may no longer show apps like Netflix w/ Android 11+ (developers can 'exclude devices from their app's distribution based on their device integrity . Device exclusion is based on the latest device integrity verdict that the Play Store app receives from the Play Integrity API') despite in-app settings showing Play Protect 'Device is certified' result.

I'm guessing that the 'passing' messages based on the old SafetyNet API are likely to realigned soon.

A workaround that evidently allows Play Integrity API attestation to pass (and solve Wallet / Play Store issues also) has been discovered. It involves spoofing an earlier certified ROM, generally by using MagiskHide Props Config module to change fingerprint prop to one for Android 10 or earlier.

Undoubtedly other apps will begin to detect broken deviceIntegrity and fail or limit functions as they migrate to the new Play Integrity API.

A 'Universal deviceIntegrity Fix for PI API' will evidently require more understanding / research into how the fingerprint prop is used, and possibly other new behaviours.

**Comment by HuskyDG** [comment]
No solution to fake bootloader status thrown from hardware attestation

**Comment by pndwal** [comment]
> No solution to fake bootloader status thrown from hardware attestation

Well you _know_ thats irrelevant while Universal SafetyNet Fix can achieve fallbacks to basic attestation... 🙄

If Google apps affected _are_ using Play Integrity's STRONG_INTEGRITY device_recognition_verdict (the one having "a strong guarantee of system integrity such as a hardware-backed proof of boot integrity") which seems likely, then USNF is certainly achieving these fallbacks for Play Integrity API as well as for SafetyNet.

For example, cards can be added to GPay/Wallet for contactless payments where a fingerprint prop is selected that both satisfies both the old CTS Profile match and new Play Integrity DEVICE_INTEGRITY verdict. Many on Android 11+ now need to select an Android 10 (or earlier) fingerprint prop value to bypass Play integrity failed DEVICE_INTEGRITY, but the fact this failure wil also occur where the selected fingerprint  
fails CTS Profile match (or USNF is simply disabled) indicates that STRONG_INTEGRITY verdict is effectively being bypassed by USNF...

A Universal Play Integrity Fix will not "solve bootloader status thrown from hardware attestation" when this is properly enforced any more than Universal SafetyNet Fix can... But that's beside the point; it hasn't happened yet...

**Comment by HuskyDG** [comment]
@pndwal no need to explain, we knew how it work, it can and it can't

**Comment by pndwal** [comment]
Then please stop spamming this issue...

**Comment by HuskyDG** [comment]
What is your "spamming" definition?

> Undoubtedly other apps will begin to detect broken TEE etc / fail as they migrate or begin integrating the Play Integrity API.

Btw, you might not pass strong integrity in this case.

**Comment by pndwal** [comment]
> What is your "spamming" definition?
Things not relevant to the issue...

However it is now clear that STRONG_INTEGRITY is not  being used as yet by google apps or bypassed successfully, so you observation may be relevant to that despite not having any bearing on the need for a better workaround to allow Play Integrity API DEVICE_INTEGRITY attestation to pass and solve Wallet / Play Store and potential bank app issues.

> > Undoubtedly other apps will begin to detect broken TEE etc / fail as they migrate or begin integrating the Play Integrity API.
> 
> Btw, you might not pass strong integrity in this case.

Sure... But I doubt banks will want to exclude all devices launched with Android 7 and earlier, as well as many late OnePlus and other devices any more than Google does... I'm guessing this won't be an issue for a while yet as critical mass of devices with working keystore in hardware for STRONG_INTEGRITY verdict enforcement is still a way off...

**Comment by denunity** [comment]
use safetynet fix mod [safetynet fix mod](https://github.com/kdrag0n/safetynet-fix/files/9356078/safetynet-fix-v2.3.1-MOD.zip)

**Comment by pndwal** [comment]
> use safetynet fix mod [safetynet fix mod]...

Please see @Displax link for Play Integrity Api bypass #207 above; Pending fix for this and other issues per:
https://github.com/kdrag0n/safetynet-fix/pull/207#issuecomment-1194661739

**Comment by Zibri** [comment]
Google pay is horrible in every aspect... in the end for contactless payments "Cards" is better.

**Comment by pndwal** [comment]
Guess this shouldn't be called 'Universal Play Integrity Fix' as clearly we can't make strongIntegrity verdict pass...

Changed issue description to reflect that proposed fix is really a 'Universal deviceIntegrity Fix for PI API' only... (basicIntegrity can be assumed if deviceIntegrity is passing)

PI strongIntegrity verdict may still be invoked by banks at some point in future with not obvious 'fix' for modders on the horizon... 😭
