### ISSUE TITLE
Weird bug 

### ISSUE THREAD

**Issue by skelletR** [kdrag0n/safetynet-fix#210]
I have Xiaomi Poco X3 NFC android 10 latest magisk 25.2 zygisk enable with your module latest version only installed and pass safetynet, can't see Netflix on Google Play but the strange is some games also disappear, and the very strange is my other phone, Sony Xperia Z5 android 7.1.1 have the same with my Xiaomi magisk and module, and the Netflix is on Google Play and the other games, I don't understand

**Comment by pndwal** [comment]
Playstore now uses new Play Integrity API.

An extra triger is needed to bypass hardware keystore attestation for this for many devices, especially w/ A11+. With Android 10 and below USNF often works as-is...

A Universal Play Integrity Fix is in the works:

@displax has already posted his unofficial modded USNF in its XDA thread; working for most users...

**Comment by HuskyDG** [comment]
@pndwal what a pity 😥

**Comment by skelletR** [comment]
Oh, understand, I read about this, my old phone Sony Xperia Z5 android 7.1.1 only the strong don't pass in Play Integrity API check but my new phone Xiaomi Poco X3 NFC android 10 pass only the basic
