### ISSUE TITLE
Req version that doesn't append a space character to the device model name

### ISSUE THREAD

**Issue by starcms** [kdrag0n/safetynet-fix#211]
First of all, thank you for all of your hard work and time for making this module!

However, with the new Play Attestation API, the device won't meet MEETS_DEVICE_INTEGRITY due to the space character being appended to the device model name by your module.

**Could you please release a version for those of us who's phones don't support Hardware Based Attestation from the factory and that doesn't add the space character?** (this includes nearly all OnePlus devices except possibly those that shipped with A12)

This would forego the need of also having to also use the MagiskHidePropsConf (MHPC) module to change the fingerprint with a certified one in order to pass new Play Attestation API and specifically MEETS_DEVICE_INTEGRITY -- which MHPC accomplishes by not only changing the fingerprint (which isn't needed in this case) but also changes the device model name back to stock (or to match the certified fingerprint chosen to be more accurate), removing the appended space character to the model name that your module adds -- and thereby allowing the new Play Attestation API to pass MEETS_DEVICE_INTEGRITY. 

In my case, running a OnePlus 7T with the latest release of OOS11 for it, I don't have to choose a certified Android 10 fingerprint, just the certified Android 11 one for the same device so that MHPC changes the device model name back to stock (without the appended space character).

I know this solution won't work for those with the v newest phones that actually have Hardware Based Attestation and for the moment they will need to continue to use your module as-is in addition to MHPC to change the fingerprint to certified one for an older version of Android which doesn't support Hardware Based Attestation (which, as I mentioned before also sets the device model name to stock (to match the fingerprint) removing the appended space character. So even in this case, I'm pretty sure appending a space to the device model name isn't helping with the new Play Attestation API because it will cause any device to fail MEETS_DEVICE_INTEGRITY.

So if you could maybe simply update your module to stop appending the space character for everyone or at least make a slightly modified version that doesn't append it, that would be fantastic -- especially for those of us who's phones only support BASIC attestation and not Hardware Based from the factory.

Thanks again very much for all your hard work,
Look forward to hearing what you think,
Best regards,
Chris

**Comment by Displax** [comment]
https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD
