### ISSUE TITLE
Latest Android Security Patch

### ISSUE THREAD

**Issue by r3shahbazi** [kdrag0n/safetynet-fix#212]
using latest version of module
![Screenshot_20220813-172943_Yet Another SafetyNet Attestation Checker.png](https://user-images.githubusercontent.com/86329230/184496057-63e46b04-cb02-44a2-83aa-51a66a969d4d.png)

**Comment by darryllin** [comment]
Did you uninstall USNF, reboot, reinstall USNF 2.3.1 mod, clear data for play store? Use this version: 
https://github.com/kdrag0n/safetynet-fix/issues/203#issuecomment-1200397185

Works for me after upgrade.

**Comment by cptmacp** [comment]
this seem to be an issue , i guess we have to wait for kdragon to fix the issue .

PS :

current security patch has some new API and SN gonna be depricated soon .

**Comment by 0purple** [comment]
Can report same on Lancelot crDroid 8.8. Modded version doesn't help

**Comment by Displax** [comment]
> Can report same on Lancelot crDroid 8.8. Modded version doesn't help

Bad ROM

**Comment by 0purple** [comment]
> > Can report same on Lancelot crDroid 8.8. Modded version doesn't help
> 
> Bad ROM

8.7 worked fine, merging latest security patch breaks SafetyNet. Wym bad ROM?

**Comment by kdrag0n** [comment]
You need fingerprint fixes: https://github.com/kdrag0n/safetynet-fix/blob/master/README.md#universal-safetynet-fix
