### ISSUE TITLE
Pixel 6 stable 13 - Safetynet Fail

### ISSUE THREAD

**Issue by jacbrooks** [kdrag0n/safetynet-fix#213]
Updated Pixel 6 Pro to 13. Safetynet is failing.

![Screenshot_20220815-190338](https://user-images.githubusercontent.com/2767600/184735277-ae615cc1-cf91-42e9-b6ba-7dbea36ea79a.png)

**Comment by Displax** [comment]
SELinux status?

**Comment by natawi** [comment]
YASNAC SafetyNet test passes on my Pixel 5A. However, I am unable to install apps such as Netflix from the Play Store, even after clearing Play Store data.

**Comment by natawi** [comment]
#207 Seems to have a temporary fix until a more efficient fix is released.

**Comment by jacbrooks** [comment]
SELinux status? Permissive
When I switched it to enforcing it passes. 

![Screenshot_20220816-090119](https://user-images.githubusercontent.com/2767600/184885998-1531a904-52f1-4d38-ba10-0929937a86f1.png)
