### ISSUE TITLE
Android  13

### ISSUE THREAD

**Issue by 565465474575** [kdrag0n/safetynet-fix#218]
Please support android 13, when i upgrade to android 13 this module doesn't work anymore it doesn't work anymore.

mobile phone model redmi k50pro
Android version 13
Mobile phone system ROM V13.1.22.8.25.DEV 开发版
![Screenshot_2022-08-27-13-45-51-937_com topjohnwu magisk](https://user-images.githubusercontent.com/73727313/187016789-dd9b646d-9384-4664-a298-3a2061c3bf13.jpg)

![Screenshot_2022-08-27-13-45-18-461_com android vending](https://user-images.githubusercontent.com/73727313/187016791-1cfc244f-6de5-4d15-a0e8-99febc29df47.jpg)
![Screenshot_2022-08-27-13-42-42-999_com android settings](https://user-images.githubusercontent.com/73727313/187016793-395868cb-aa9f-442f-9ab7-f309933b2203.jpg)

**Comment by chrissammy** [comment]
On Google Pixel with Android 13 no problems.
Try reinstall/reflash.

**Comment by GeorgeV220** [comment]
Same issue with ArrowOS 13

**Comment by denunity** [comment]
use mod safetynet fix It all works for me []()https://github.com/kdrag0n/safetynet-fix/files/9356078/safetynet-fix-v2.3.1-MOD.zip

**Comment by nugget-tn** [comment]
@denunity how did you come up with this cause this actually worked for me.
