### ISSUE TITLE
It's in not working on magisk 25.2

### ISSUE THREAD

**Issue by bLACKbEAST0** [kdrag0n/safetynet-fix#219]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Device info**
Device model:
Android version:
ROM name/version:

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by jwhb** [comment]
It works without any problem on LineageOS 19-20221230-NIGHTLY-polaris.

Zygisk should be activated and then it requires a reboot.

> Install the downloaded module in Magisk Manager, then enable Zygisk in Magisk settings.

**Comment by kdrag0n** [comment]
Closing due to missing info.
