### ISSUE TITLE
Fingerprint not working 

### ISSUE THREAD

**Issue by ghost** [kdrag0n/safetynet-fix#220]
I have a one plus 7 pro with lineage OS. I have recently rooted it with magisk however the fingerprint to unlock the lock screen and creating new finger prints does not work. I have seen that there are fixes related to oxygen os / color os for the fingerprints with the safetynet-fix module however with this module as well as hide props config nothing works unfortunately. Would like some guidance thanks.

**Comment by zboq** [comment]
I just upgaded Oneplus 7T pro to android 12 and safetynet fix 2.3.1 causes fingerscanner not working/unlocking on lockscreen.
I'we seen, that this should be fixed, but somehow it's not working on OP7T pro.
Tested it and when disabled module, finger scanner works again. After enabling it, stops working. 
I guess, module need some more updates ?

**Comment by 150d** [comment]
Hi,

same problem here:

device: Oneplus Nord
OS: OxygenOS12.1 (AC2003_11_F.16, EU-Version)
Magisk: 25.2
USNF module: v2.3.1

The module works perfectly for hiding root, but once it is enabled, the fingerprint sensor can't log in any more. It appears to scan, blink, vibrates and so on, but it doesn't recognize a finger and finally forces login via PIN. If I disable the USNF module and reboot, the fingerprint sensor returns to full functionality immediatly (but of course root is no longer hidden and SafetyNet no longer passed, as shown by YASNAC.)

(Before the update to Android v12 I had Magisk v23 running on Android v11 without USNF module, just using MagiskHide. This did not pass all Check-Tests, but none of my usual apps complained either. Fingerprint sensor used to be fine though.)

**Comment by Displax** [comment]
> Hi,
> 
> same problem here:
> 
> device: Oneplus Nord
> OS: OxygenOS12.1 (AC2003_11_F.16, EU-Version)
> Magisk: 25.2
> USNF module: v2.3.1
> 
> The module works perfectly for hiding root, but once it is enabled, the fingerprint sensor can't log in any more. It appears to scan, blink, vibrates and so on, but it doesn't recognize a finger and finally forces login via PIN. If I disable the USNF module and reboot, the fingerprint sensor returns to full functionality immediatly (but of course root is no longer hidden and SafetyNet no longer passed, as shown by YASNAC.)
> 
> (Before the update to Android v12 I had Magisk v23 running on Android v11 without USNF module, just using MagiskHide. This did not pass all Check-Tests, but none of my usual apps complained either. Fingerprint sensor used to be fine though.)

Use my mod: https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.0

**Comment by 150d** [comment]
Perfect! Fingerprint working again, Safetynet (Basic) still passing.

Thank you!!
