### ISSUE TITLE
Google PAY says the phone is rooted.

### ISSUE THREAD

**Issue by Zibri** [kdrag0n/safetynet-fix#223]
While the "fix" works with mac donald app, it does not with google pay.
Google pay says the phone is rooted.

**Comment by Zibri** [comment]
![Screenshot_2022-10-05-15-26-29-982_rikka safetynetchecker](https://user-images.githubusercontent.com/855176/194072170-fa059f3b-dca3-495d-9386-0dd2cf42d32d.jpg)

**Comment by atgodfrey** [comment]
Similar issue. I am passing Safetynet (basic and cts), have added Play Store/Wallet/Play Services/Play Protect Service to denylist, cleared data on airplane more, but Wallet still knows I'm rooted. On a Pixel 5 w/ Android 13.

**Comment by kdrag0n** [comment]
Duplicate of #204

**Comment by joeky888** [comment]
This reddit comment fixed my google pay issue. Hope this helps!

https://www.reddit.com/r/Magisk/comments/xm5fjz/comment/ipwgs9j
