### ISSUE TITLE
Pixel 7 Pro CTS profile fail

### ISSUE THREAD

**Issue by ZerkerEOD** [kdrag0n/safetynet-fix#224]
Hello I am getting CTS profile fail and I tried the modded version also. Is there a way to fix this?

**Comment by kafisc1** [comment]
Same issue on P7.

**Comment by ender-zhao** [comment]
Try replacing the code inside service.sh with this.
It's work with my Pixel 7 Pro
````
#!/system/bin/sh
# Conditional MagiskHide properties

maybe_set_prop() {
    local prop="$1"
    local contains="$2"
    local value="$3"

    if [[ "$(getprop "$prop")" == *"$contains"* ]]; then
        resetprop "$prop" "$value"
    fi
}

# Magisk recovery mode
maybe_set_prop ro.bootmode recovery unknown
maybe_set_prop ro.boot.mode recovery unknown
maybe_set_prop vendor.boot.mode recovery unknown

# MIUI cross-region flash
maybe_set_prop ro.boot.hwc CN GLOBAL
maybe_set_prop ro.boot.hwcountry China GLOBAL

resetprop --delete ro.build.selinux

# SELinux permissive
if [[ "$(cat /sys/fs/selinux/enforce)" == "0" ]]; then
    chmod 640 /sys/fs/selinux/enforce
    chmod 440 /sys/fs/selinux/policy
fi

# Late props which must be set after boot_completed
{
    until [[ "$(getprop sys.boot_completed)" == "1" ]]; do
        sleep 1
    done

    # avoid breaking Realme fingerprint scanners
    resetprop ro.boot.flash.locked 1

    # avoid breaking Oppo fingerprint scanners
    resetprop ro.boot.vbmeta.device_state locked

    # avoid breaking OnePlus display modes/fingerprint scanners
    resetprop vendor.boot.verifiedbootstate green

    # makes bank apps and Google Pay happy
    resetprop sys.oem_unlock_allowed 0

    # avoid breaking encryption, set shipping level to 32 for devices >=33 to allow for software attestation.
    if [[ "$(getprop ro.product.first_api_level)" -ge 33 ]]; then
        resetprop ro.product.first_api_level 32
    fi

}&

````

![Screenshot_20221022-172909](https://user-images.githubusercontent.com/77391690/197332062-41345dc9-69c2-40d1-b330-87ebc06b0878.png)

**Comment by schumski** [comment]
> Try replacing the code inside `service.sh` with this. It's work with my Pixel 7 Pro
> 

It worked on mine too. You are my hero. Thanks!

**Comment by ender-zhao** [comment]
> > Try replacing the code inside `service.sh` with this. It's work with my Pixel 7 Pro
> 
> It worked on mine too. You are my hero. Thanks!

But this way only can help you pass this test. You still unable download Netflix or use GPay.
And I just found a fork of safetynet-fix, that module is fixed these problem.
https://github.com/Displax/safetynet-fix/releases

**Comment by erdy232** [comment]
> > > Try replacing the code inside `service.sh` with this. It's work with my Pixel 7 Pro
> > 
> > 
> > It worked on mine too. You are my hero. Thanks!
> 
> But this way only can help you pass this test. You still unable download Netflix or use GPay. #210 And the luckily, I just found a fork of safetynet-fix, that module is fixed these problem. https://github.com/Displax/safetynet-fix/releases

GPay still doesn't work for me with Displax's fork for Pixel 7. Some time after installation, it also fails the CTS profile match.

**Comment by Techwolf12** [comment]
For me, the fix in https://github.com/kdrag0n/safetynet-fix/issues/224#issuecomment-1287693940 was also a requirement to get GPay working, you also have to clear data/cache from Google Play Store/Google Wallet and suddently, it would work for me!

**Comment by M3gaFr3ak** [comment]
> For me, the fix in [#224 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/224#issuecomment-1287693940) was also a requirement to get GPay working, you also have to clear data/cache from Google Play Store/Google Wallet and suddently, it would work for me!

I used [the fix ender-zhao mentioned](https://github.com/kdrag0n/safetynet-fix/issues/224#issuecomment-1295059469) and applied the [#224 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/224#issuecomment-1287693940) fix. Works with netflix and gpay

**Comment by T0PGlitch3r** [comment]
you don't need to do any of that i have the Pixel 7a and i was having the same problem until i did this i downloaded and installed the universal safety net fix and also installed magiskhideprop then installed termux here is what you have to do:
su
props
choose 1
then choose f
then 7
then choose 29 
the yes then when it says reboot then reboot
I know it says Google Pixel 6  pro but it works i now have netflix and wallet working on my phone

**Comment by ZerkerEOD** [comment]
> you don't need to do any of that i have the Pixel 7a and i was having the same problem until i did this i downloaded and installed the universal safety net fix and also installed magiskhideprop then installed termux here is what you have to do: su props choose 1 then choose f then 7 then choose 29 the yes then when it says reboot then reboot I know it says Google Pixel 6 pro but it works i now have netflix and wallet working on my phone

Yes, it's been fixed which is why it's closed.

**Comment by T0PGlitch3r** [comment]
ok

**Comment by missionmankind** [comment]
where is service.sh found? forgive me i dont know where or what this is. 
I have FX Explorer. 
Id like to try to copy and paste this code.
I have a Pixel 7 Pro as well thats failing CTS profile match.

**Comment by ghost** [comment]
**I MADE A WORKING SAFETYNET FIX!**
*https://github.com/vepexlegit/safetynet-working-fix*
**READ CAREFULLY README.md**

**Comment by crok** [comment]
> 

Why rar? Why do you do it in this shady and clunky way? Why don't you simply make a PR or explain what you did in your "fix"?

**Comment by crok** [comment]
> https://github.com/vepexlegit/safetynet-working-fix

Why rar? Why do you do it in this shady and clunky way? Why don't you simply make a PR or explain what you did in your "fix"?

**Comment by Tragen** [comment]
I wanted to compare the forks but no source code. :(
