### ISSUE TITLE
Unsupported CPU architecture

### ISSUE THREAD

**Issue by dubl3a** [kdrag0n/safetynet-fix#23]
Samsung SM-T510 2019 model
Stock Android 9
TWRP and Magisk installed

When I try to install I get the following:

- Extracting module files
Unsupported CPU architecture: armeabi-v7a
! Installation failed

**Comment by dubl3a** [comment]
2.0.0-test2 worked

**Comment by andrikos** [comment]
> 2.0.0-test2 worked

Where did you find that version? 
I get your same message in my Moto G6
