### ISSUE TITLE
Oneplus 7t oos 12 fingerprint reader not working

### ISSUE THREAD

**Issue by thebestnom** [kdrag0n/safetynet-fix#230]
**Describe the bug**
After installing the latest version fingerprint reader stopped working, disabling the module didn't help, only uninstalling it, but after uninstalling it did work, which helped me be sure that the problem is this module specifically 

**To reproduce**
1. Install module
2. Try unlocking anything with fingerprint (not matter locksreen or bank app)
3. Not working
4. (I know the sensor somewhat works as I can add new fingerprints on the settings and only using it doesn't work and uninstalling restore fingerprint)

**Expected behavior**
Fingerprint unlocking stuff

**Device info**
Device model: OnePlus 7t HD1900
Android version: 12
ROM name/version: HD1900_11_F.17 (OxygenOS/rebranded ColorOS)

**Logs**

**Additional context**

**Checklist**
- [x] All information is present
- [ ] Logs are attached
- [x] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by thebestnom** [comment]
Ill try that today, but why he didn't open a pr?

**Comment by thebestnom** [comment]
(I used clean version from github release)

**Comment by thebestnom** [comment]
Oh, there is a PR 😅

**Comment by pndwal** [comment]
He did... Some time ago now... Mentioned in XDA post...

Just linked comment from @ kdrag0n in that PR... See edited post above...

**Comment by pndwal** [comment]
Please comment here if @Displax fix works properly for you...

**Comment by thebestnom** [comment]
Of course, Ill test and update in the evning

**Comment by thebestnom** [comment]
(didn't had time today, Ill try tomorrow 😅)

**Comment by thebestnom** [comment]
Ok, that's weird, found out that actually enabling MagiskHideProps was actually the problem (decided to first hide props to pass cts firs)

**Comment by thebestnom** [comment]
The mod works as a charm, can now use google wallet and fingerprint sensor! Thanks 😄
@pndwal

**Comment by thebestnom** [comment]
Not sure if I should close this issue or not as I needed outside mod to fix this 😅

**Comment by pndwal** [comment]
> Ok, that's weird, found out that actually enabling MagiskHideProps was actually the problem (decided to first hide props to pass cts firs)

Don't set any fingerprint in MHPC as @Displax said...

> Not sure if I should close this issue or not as I needed outside mod to fix this 😅

You can close it... @Displax's PR already includes a proper fix for OnePlus, and & @kdrag0n has requested him to submit another if needed... 
https://github.com/kdrag0n/safetynet-fix/pull/207

**Comment by thebestnom** [comment]
Didn't set just tried first that before

Thanks again!

**Comment by Kuuhhl** [comment]
Still an issue for me.

When the module is enabled, fingerprint won't unlock my phone (though registering new fingerprint in the settings works as expected).
If I disable the module, it unlocks my phone as usual.

OS: HD1903_11_F.17
Magisk-Version: 831a398b
Safetynet-Fix-Version: v2.4.0

**Comment by FelemixX** [comment]
> Still an issue for me.
> 
> When the module is enabled, fingerprint won't unlock my phone (though registering new fingerprint in the settings works as expected). If I disable the module, it unlocks my phone as usual.
> 
> OS: HD1903_11_F.17 Magisk-Version: 831a398b Safetynet-Fix-Version: v2.4.0

UP
