### ISSUE TITLE
Not working in MIUI14(android 13)

### ISSUE THREAD

**Issue by chenxiccc** [kdrag0n/safetynet-fix#236]
Device: Xiaomi 11 Ultra
OS: MIUI 14.0.22.12.8.DEV (Android 13)

I've wiped Google play store, google service framework, google play service 's data and reboot the phone.

But Safetynet-fix 2.3.1 does not work , Google play shows device is not certificated.

**Comment by Displax** [comment]
Use my MOD version

**Comment by crok** [comment]
> Use my MOD version

Hi Displax, by any change, from the top of your head.. do you know perhaps what's the difference between your version (v2.3.1-MOD_2.0) and [HuskyDG's v2.3.1 MOD 2](https://github.com/HuskyDG/safetynet-integrity-fix/releases/tag/v2.3.1-safetynet-mod.2)?

**Comment by chenxiccc** [comment]
> Use my MOD version
> https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.0

Thanks！It works!

**Comment by Hot12345** [comment]
> Use my MOD version https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.0

Hi Displax, first of all super thanks for your devp.
Can I donate to ya?
Second, can I use your fork as a main build of over the kdragon build?

**Comment by Hot12345** [comment]
> Use my MOD version https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.0

Could you explain what you changed in your updated version? Because I want to make a donation to ya work. For supporting this wonderfull module.

**Comment by kdrag0n** [comment]
Fixed in v2.4.0
