### ISSUE TITLE
com.google.android.gms.unstable CPU usage

### ISSUE THREAD

**Issue by Theo-user** [kdrag0n/safetynet-fix#238]
I've narrowed down a cause of battery drain from com.google.android.gms.unstable process that only shows up with this module. Uses 12.5% CPU indefinitely. It doesn't load at startup but something does trigger it eventually.

Poco F3, Crdroid 8.12, nikapps.

Latest Magisk/Delta regardless of Magisk Hide or Shamiko.

Killing the process does stop it for a while but shows up again. Disabling gms intents does nothing.

**Comment by Wittoy** [comment]
try to remove `com.google.android.gms.unstable` from Magisk Hide Denylist?

**Comment by Theo-user** [comment]
@Wittoy it made no difference.

![Screenshot_20221228-114938_Franco Kernel Manager](https://user-images.githubusercontent.com/75871295/209808120-97b2fad5-8e0c-48b8-9f61-48cd7d96ff31.png)

**Comment by Theo-user** [comment]
> overlay module

Regarding font, it's just the stock one whatever Crdroid uses. What do you mean by overlay module?

Here's my modules

![Screenshot_20230101-182349_Settings](https://user-images.githubusercontent.com/75871295/210181059-955f33e5-de40-4757-ac52-bbaef39a1c62.png)

**Comment by Theo-user** [comment]
Disabling the adreno driver fixed it.

Now using overlayfs version and the issue is still fixed.

Thanks.

![Screenshot_20230103-145835_Settings](https://user-images.githubusercontent.com/75871295/210382820-37180ab6-7106-47b2-a09a-cb97dcfe2342.png)
