### ISSUE TITLE
[Question] Does this only work on Samsung ROMs?

### ISSUE THREAD

**Issue by Aholicknight** [kdrag0n/safetynet-fix#24]
Sorry for asking such a stupid question but would this work with LineageOS to make SafetyNet pass? Thank you.

**Comment by kdrag0n** [comment]
It will work on LineageOS.

Samsung ROMs are hit-or-miss and generally don't work well.

**Comment by Aholicknight** [comment]
Thank you very much; the first issue that I created for this repo was me using a Samsung ROM, which was probably why my phone kept soft-restarting...on LineageOS, the phone does not soft-reset and still passes SafetyNet.

**Comment by Aholicknight** [comment]
Sorry for replying to a closed issue but @kdrag0n does this also work on Google Pixel devices mostly the Pixel 5? Thanks.

**Comment by kdrag0n** [comment]
Yes. Please do not use GitHub issues for support.
