### ISSUE TITLE
Google Wallet crashes on startup on Pixel 7

### ISSUE THREAD

**Issue by aliantonio** [kdrag0n/safetynet-fix#245]
Wallet crashes immediately on startup. 

Magisk: 25.2 stable
safetynet-fix: 2.4.0

**Comment by kdrag0n** [comment]
Please share a logcat. From the issue template:

> **Logs**
> Connect your phone to a computer and run adb logcat > issue.log. Attach the log file to this issue.

**Comment by aliantonio** [comment]
Sorry about that. Attaching it here. 
[issue.log](https://github.com/kdrag0n/safetynet-fix/files/10377086/issue.log)

**Comment by kdrag0n** [comment]
Duplicate of #163. Solution in https://github.com/kdrag0n/safetynet-fix/issues/163#issuecomment-1066020819.
