### ISSUE TITLE
Regression of #196 (fingerprint sensor not working)

### ISSUE THREAD

**Issue by fzechert** [kdrag0n/safetynet-fix#254]
**Describe the bug**
Instead of using the released version 2.3.1, I used a special version mentioned in #196.
I recently (since Wednesday 2023-01-25 observed intermittent problems with Google Pay (usually fixed by a phone restart for a short a mount of time), as mentioned in the issue: #248.

In hopes to remediate this problem, I upgraded the module to the latest version 2.4.0.

Unfortunately with this new version, the problem with the malfunctioning fingerprint sensor is back.

**To reproduce**
1. Install latest version v2.4.0 in magisk
1. Reboot phone
2. Fingerprint sensor no longer recognizes fingerprints

**Expected behavior**
The functionality of the fingerprint sensor should not be affected and it should keep working.
The fix from the special 2.3.1 version mentioned in #196 is not included or no longer works in version 2.4.0.

**Device info**
Device model: OnePlus 7T H1903
Android version: 12, Security patch from August 5, 2022
ROM name/version: HD1903_11_F.17

**Additional context**
The problem was originally fixed in a special version 2.3.1 mentioned in #196.
The problem exists again with updated version 2.4.0.
The intermittent Google Wallet Problem mentioned in #248 can be observed with both versions.

**Checklist**
- [x] All information is present
- [ ] Logs are attached
- [x] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

If I can provide you with any more details or help by testing out fixes, I am happy to help.
Thank's for all your work on this Safetynet Fix Module.

**Comment by kdrag0n** [comment]
Expected behavior. The OP fingerprint fix was merged after v2.4.0 and will be included in the next release.
