### ISSUE TITLE
Phone crashes after startup when using shamiko + safetynet-fix

### ISSUE THREAD

**Issue by fluffy-git** [kdrag0n/safetynet-fix#260]
When using shamiko and safetynet-fix on Android 13 with OneUi 5 the phone crashes after activating the modules and rebooting

**Comment by edgvrl** [comment]
It probably is, but i can't seem to find where i could submit an issue for shamiko

**Comment by tuyennn** [comment]
@fluffy-git on their telegram, but beware they are a bunch of geeks

**Comment by edgvrl** [comment]
well, then i don't know what to do, but thanks for helping me
