### ISSUE TITLE
FingerPrint not working for OnePlus 7t oxygen OS 12 F.20

### ISSUE THREAD

**Issue by JayeshI97** [kdrag0n/safetynet-fix#264]
**Describe the bug**
FingerPrint cannot be recognised to unlock phone lock or the banking app lock even after using safety net 2.4 or any previous version .

**To reproduce**
1. Go to 'magisk manager
2. Install safety net for zygisk
3.reboot
4.enter password for pattern lock again and try to unlock with fingerprint 

**Expected behavior**
Want fingerprint to work again.

**Device info**
Device model:OnePlus 7T indian HD1901
Android version:12.0
ROM name/version:HD1901_11_F.20

**Logs**
C
I am getting the logs since it is taking some time will attach if needed 

**Additional context**

**Checklist**
- [x] All information is present
- [ ] Logs are attached
- [x] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by Displax** [comment]
https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.2

**Comment by JayeshI97** [comment]
> https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.2

Thank you worked for me

**Comment by JayeshI97** [comment]
Please use Displax stated ver might solved the issue 
Since it is working for me closing this
