### ISSUE TITLE
Disappeared again 

### ISSUE THREAD

**Issue by VisionR1** [kdrag0n/safetynet-fix#272]
**Describe the bug**
I pass the safetynet and the new but Netflix and other disappeared again from Google Play Store.

**To reproduce**

**Expected behavior**
I have riru and safetynet 2.4.0

**Screenshots**

**Device info**
Device model: Xiaomi Poco X3 NFC 
Android version: 10
ROM name/version: 12.0.8.0 EEA

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by pascallj** [comment]
Apparently changes were made to the Play Integrity API. It failed the DEVICE_INTEGRITY for me. There is #261 but for some reason it has been marked as draft. 

However Displax' version 2.4.0-MOD_1.2 worked for me. Had to clear Google Play Services data for Netflix to reappear in the Play Store.

**Comment by skelletR** [comment]
> 

Yeah, I don't change anything, magisk 23 riru snd safetynet 2.4.0, i clear Google Play Services data and Netflix reappear in the play store

**Comment by VisionR1** [comment]
> Apparently changes were made to the Play Integrity API. It failed the DEVICE_INTEGRITY for me. There is #261 but for some reason it has been marked as draft.
> 
> However Displax' version 2.4.0-MOD_1.2 worked for me. Had to clear Google Play Services data for Netflix to reappear in the Play Store.

Yeah, I don't change anything, magisk 23 riru and safetynet 2.4.0, i clear Google Play Services data and Netflix reappear in the play store

**Comment by pascallj** [comment]
Oh maybe that would have worked for me as well from get-go, but I switched to Displax right away. Glad you got it sorted out.

**Comment by VisionR1** [comment]
> Oh maybe that would have worked for me as well from get-go, but I switched to Displax right away. Glad you got it sorted out.

Yeah maybe, thanks for the advice, i have the ported version of safetynet 2.4.0 for riru
