### ISSUE TITLE
Is a bug with desynchronization or just me?

### ISSUE THREAD

**Issue by VisionR1** [kdrag0n/safetynet-fix#277]
First of all, i ask if this is a issue and if the @kdrag0n update the original module and after the other person ported to another. I have Xiaomi Poco X3 NFC android 10 with magisk 23 with riru 26.1.3 and module 2.4.0 ported for riru from @HuskyDG. Before 1 month work the 2.4.0, but when the Google Play service have a update, (have update 4-5 time this month) after the update, safetynet desynchronization by itself every time, i think, must clear some time the data and after 2-3 times work again, but is time consuming all this, any solution? i mentioned because of this #261

**Comment by crok** [comment]
> ..android 10 with _magisk 23_ with _riru 26.1.3_ and module 2.4.0 _ported for riru from @HuskyDG_

Then why do you report this here? The Magisk you are using is so outdated that it's almost 2 whole years old, not even including Zygisk which is the crucial base of the module developed by kdrag0n.. oh, you aren't even using the module BUT a mod of the module made by a completely different developer based on Riru.. smh.

**Comment by VisionR1** [comment]
> > ..android 10 with _magisk 23_ with _riru 26.1.3_ and module 2.4.0 _ported for riru from @HuskyDG_
> 
> Then why do you report this here? The Magisk you are using is so outdated that it's almost 2 whole years old, not even including Zygisk which is the crucial base of the module developed by kdrag0n.. oh, you aren't even using the module BUT a mod of the module made by a completely different developer based on Riru.. smh.

Yeah, i report here, because first the @kdrag0n need to update the module if this is a issue i mention and after the @HuskyDG ported the update for riru

**Comment by AllenChangMusic** [comment]
You provided no bug report, logs, etc. You are using unsupported magisk AND a ported module not managed by kdrag0n.
I'm not exactly sure what logic you think you'd get help here. 
There's a reason riru was dropped... 
This issue should be closed...

**Comment by AllenChangMusic** [comment]
You provided no bug report, logs, etc. You are using unsupported magisk AND a ported module not managed by kdrag0n.
I'm not exactly sure what logic you think you'd get help here. 
There's a reason riru was dropped...

**Comment by VisionR1** [comment]
> You provided no bug report, logs, etc. You are using unsupported magisk AND a ported module not managed by kdrag0n. I'm not exactly sure what logic you think you'd get help here. There's a reason riru was dropped... This issue should be closed...

Because only here can report, and the original safetynet must update first and after the all other ported module, and i mentioned because of this #261

**Comment by AllenChangMusic** [comment]
Okay, let me make this simple for you
1) Ports are NOT supported. kdrag0n has no idea what is included in the port. 
2) You are using unsupported magisk/riru, way too old for any support anyways
3) What you are asking is the same as calling Apple for help with a 10-year-old Hackintosh... like come on man! Stop trying to argue this and close the issue

**Comment by VisionR1** [comment]
> Okay, let me make this simple for you
> 
> 1. Ports are NOT supported. kdrag0n has no idea what is included in the port.
> 2. You are using unsupported magisk/riru, way too old for any support anyways
> 3. What you are asking is the same as calling Apple for help with a 10-year-old Hackintosh... like come on man! Stop trying to argue this and close the issue

I know ported not supported, not ask this, just i ask to update the original safetynet to fix the desynchronization issue, i mentioned because of this #261

**Comment by AllenChangMusic** [comment]
I hope you understand that the whole purpose of github is because the code source is present. IF your port writer wanted to, they can build it from the source code, there's no need for kdrag0n to build a zygisk version before they can do a riru version. I hope that helps you understand how this works...

**Comment by VisionR1** [comment]
> I hope you understand that the whole purpose of github is because the code source is present. IF your port writer wanted to, they can build it from the source code, there's no need for kdrag0n to build a zygisk version before they can do a riru version. I hope that helps you understand how this works...

Yeah, exactly, for that i ask if this is a issue and if the @kdrag0n update the original module and after the other person ported to another, because the @Displax have some changes to want to merge in the original and after update, read this #261

**Comment by AllenChangMusic** [comment]
Again, you are missing the point. Displax's changes are ALSO on github. IF your port maker wants to use it, he doesn't need for kdragon to update anything. I'm not sure if you understand how open source works. And stop tagging them, you are an annoyance at this point because I'm not sure if you understand how programming works.

**Comment by VisionR1** [comment]
> Again, you are missing the point. Displax's changes are ALSO on github. IF your port maker wants to use it, he doesn't need for kdragon to update anything. I'm not sure if you understand how open source works. And stop tagging them, you are an annoyance at this point because I'm not sure if you understand how programming works.

Yeah, I don't understand for that i ask all this, and i want the original safetynet, first if the kdragon approved the changes from Displax and want merge, because maybe not right and the kdragon want to fix it first and after merge like the some previous versions, for that not ported the Displax module first

**Comment by AllenChangMusic** [comment]
Okay, I think maybe you don't understand how this works. I can excuse that, you can go read up on it.
BUT, it's not about what YOU want. You have to just stop. You aren't using original safetynet anyways. Original doesn't even work on old magisk, it is based on Zygisk. 
Anything more you say right now is just embarrassing yourself more

**Comment by VisionR1** [comment]
> Okay, I think maybe you don't understand how this works. I can excuse that, you can go read up on it. BUT, it's not about what YOU want. You have to just stop. You aren't using original safetynet anyways. Original doesn't even work on old magisk, it is based on Zygisk. Anything more you say right now is just embarrassing yourself more

Yeah, I don't understand that i say, and the zygisk version must update because have the same issue, thanks for your opinion, but i want the opinion of kdragon, now my open issue have too many questions and i don't think read it

**Comment by AllenChangMusic** [comment]
Okay, I give up. You'll find that with that attitude you aren't going to get much if any help on here. Hope it works out for you!
Again with the Apple analogy, what you are saying is "my iPhone doesn't work, I want to speak to Tim Cook/Steve Jobs because I don't trust anyone else"

**Comment by skelletR** [comment]
> 

Thanks you, just hope
