### ISSUE TITLE
Keystore issues

### ISSUE THREAD

**Issue by alishchytovych** [kdrag0n/safetynet-fix#28]
Android 11 (SM-N9860 TGY) has an issue with this patch - StrongSwan VPN client (with certificates authenticaton) can't reconnect (reauthenticate) due to this patch and hangs connection. Error in the logs - keystore object is dead. Details TBD.

**Comment by kdrag0n** [comment]
Same underlying issue as #13.

**Comment by pherrman** [comment]
Thank you, I just wanted to let you know that your safetynet fix 2.0.0-test2.zip from Androidfilehost is working great on my rooted S20 Fe 5g with Android 11 and latest One UI. My bank apps are using the Knox fingerprint system and able to login. G pay also appears fine and I pass the safetynet test

Thank you very much for the update!! I am grateful for your hard work and dedication 🙏

Take care 😁
