### ISSUE TITLE
resetprop triggering root detection 

### ISSUE THREAD

**Issue by mylove90** [kdrag0n/safetynet-fix#284]
I think this could be a new challenge for all the devs here

I got some app that checks for the strong integrity called [Instapay Egypt ](https://play.google.com/store/apps/details?id=com.egyptianbanks.instapay)  
![Screenshot_20230521-113722](https://github.com/kdrag0n/safetynet-fix/assets/50009562/b2da90ef-2e63-443b-856e-e4a616d83f8a)
![Screenshot_20230521-113816](https://github.com/kdrag0n/safetynet-fix/assets/50009562/61b536e9-358a-4f2a-b33d-da411b4001c2)

My device is not even rooted....i am just using Arrow OS with unlocked bootloader.

Anyway around this ?

Many Thanks
Best Regards

**Comment by Theo-user** [comment]
Seems they're detecting the ROM/bootloader state. I'm not sure of an instapay workaround. I do believe it works on an unmodified Crdroid 8.14 without Magisk.

**Comment by mylove90** [comment]
> Seems they're detecting the ROM/bootloader state. I'm not sure of an instapay workaround. I do believe it works on an unmodified Crdroid 8.14 without Magisk.

Are you sure ?...looks like the oldest 8.x build available for my device is v8.2...can you tell me why that specific version would work?

**Comment by linux019** [comment]
You will never get Strong integrity with the unlocked bootloader. If app wants strong integrity and doesn't check security level on the server side you can only patch your app

**Comment by ghost** [comment]
There is a way to pass Strong integrity, old xiaomi.eu roms included it. But Instapay uses professional root and bootloader detections methods (using native libs). If you need to use this app you must lock your bootloader.

**Comment by Fede2782** [comment]
Try hiding Magisk it worked for my prepaid card app.
Go in Magisk settings and use hide app function, use a name like "MagicMask". Then enable denylist and put your app in denylist. Clear your app data and reopen the app. It should work now

**Comment by Theo-user** [comment]
> Try hiding Magisk it worked for my prepaid card app. Go in Magisk settings and use hide app function, use a name like "MagicMask". Then enable denylist and put your app in denylist. Clear your app data and reopen the app. It should work now

That's not getting around Instapay checks.

**Comment by AbdelrahmanMohamedDesoky** [comment]
> If you need to use this app you must lock your bootloader.

Instapay is not detecting bootloader state using hardware methods.

I can run Instapay just fine with the latest magisk alpha + Zygisk + Shamiko
but you have to disable any modules that use reset_prop/maybe_reset_prop aka USNF.

magisk modules that use `check_resetprop` or `maybe_resetprop`or `resetprop` are detected somehow.

https://github.com/kdrag0n/safetynet-fix/assets/12201594/9627c560-eff6-480c-92a2-a0abdaf701e1

As soon as I enable Universal Safety Net Fixer normal and the Displayx Mod version both result in Instapay detecting something with the environment and refusing to start with the same toast message.

**Comment by mylove90** [comment]
> > If you need to use this app you must lock your bootloader.
> 
> Instapay is not detecting bootloader state using hardware methods.
> 
> I can run Instapay just fine with the latest magisk alpha + Zygisk + Shamiko but you have to disable any modules that use reset_prop/maybe_reset_prop aka USNF.
> 
> magisk modules that use `check_resetprop` or `maybe_resetprop`or `resetprop` are detected somehow.
> 
>  instapay_works.mp4 
> As soon as I enable Universal Safety Net Fixer normal and the Displayx Mod version both result in Instapay detecting something with the environment and refusing to start with the same toast message.

So if i am getting this within unrooted custom rom then the devs of the rom had integrated USNF into the rom...how to revert that or disable it ?!

Thanks for the proofing video... really appreciate it

**Comment by AbdelrahmanMohamedDesoky** [comment]
> So if i am getting this within unrooted custom rom then the devs of the rom had integrated USNF into the rom...how to revert that or disable it ?!

I'm extremely sorry but I don't use custom ROMs so I wouldn't know either, but as you can see it works with magisk but still requires Shamiko latest version, I think it will also work unrooted. (stock rom)

the problem is there are some apps like Mcdonald app and some others like it that check using safety net API (not play integrity) and you would have to enable USNF anyway to make it work on those, so it's still a bad solution but better than nothing for the time being.

By the way, Credits goes to HuskyDG for telling us this in this issue : #253

**Comment by mylove90** [comment]
For Custom Rom devs to revert this module effect they should revert commits mentioned here : https://protonaosp.org/developers/details/safetynet
But that will break safetynet for sure...so there's no real solution.
