### ISSUE TITLE
Google Apps crashing

### ISSUE THREAD

**Issue by pcamposu** [kdrag0n/safetynet-fix#286]
**Describe the bug**
Google Apps fail to retrieve accounts, or crashes

**To reproduce**
1. Open Gmail, this directly crashes after splash

**Expected behavior**
Apps behaving normally

In magisk v26.1 The problem occurred but just by activating zygisk without having the module installed, in the canary (26102) version they fixed it, but when installing this module the problem occurs again, and I have other modules Installed that do not give this problem, so I think it is a module problem
**Device info**
Device model: Xiaomi Redmi 10A
Android version: 12
ROM name/version: LineageOS

**Comment by pndwal** [comment]
What module??

**Comment by pcamposu** [comment]
Seems like it is more related to zygisk than to the module, closing atm
EDIT: Other modules were Shamiko and nothing more

**Comment by Xris65** [comment]
Hey, did you fix this error ? I have the same issue, all google apps crashing when I flash safetynet-fix. I have LSPosed 1.9.1 installed and running with zygisk on magisk Delta.

**Comment by pcamposu** [comment]
Use Magisk Alpha or try [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix)
