### ISSUE TITLE
Update Zip Format for new Magisk Module Install

### ISSUE THREAD

**Issue by uofirob** [kdrag0n/safetynet-fix#29]
I'm unable to get Magisk to recognize the zip in order to install it.  Here are the guidelines: https://www.didgeridoohan.com/magisk/MagiskModuleIssues.  If you have an easy way around it already, please let me know!

**Comment by kdrag0n** [comment]
Only the zips in [releases](https://github.com/kdrag0n/safetynet-fix/releases/tag/v1.1.1) can be flashed. It's not possible to make GitHub source archives flashable due to the directory layout.

**Comment by uofirob** [comment]
This was the zip from the release section of GitHub. I still can't get it to open within Magisk.  Any other tips?

**Comment by kdrag0n** [comment]
You need the release zip: https://github.com/kdrag0n/safetynet-fix/releases/download/v1.1.1/safetynet-fix-v1.1.1.zip

"Source code (zip)" from GitHub Releases won't work. The release is known to be working with hundreds/thousands of users, so something is wrong on your side if that's still not recognized.

**Comment by uofirob** [comment]
Thanks for that direct link.  I guess the other one I had was the source download.  I appreciate you taking time to help me!
