### ISSUE TITLE
CTS Profile fail (hardware backed)

### ISSUE THREAD

**Issue by XanderTheDev** [kdrag0n/safetynet-fix#290]
**Describe the bug**
After installing the safetynet-fix, cts-profile check failed and the evaluation type was HARDWARE BACKED (ON YASNAC)

**To reproduce**
1. Go to 'safetynet-fix repo'
2. Click on 'download'
3. Install on Magisk: 'safety-net zip file'
4. Reboot
5. Open YASNAC and press 'Run SafetyNet Attestation'
6. CTS Fail

**Expected behavior**
CTS Pass

**Screenshots**
![Screenshot_20230707-141304_Yet Another SafetyNet Attestation Checker](https://github.com/kdrag0n/safetynet-fix/assets/101188151/252d8951-aa74-454e-8d88-6076c0bbd255)

**Device info**
Device model: SM-A525F
Android version: 13
ROM name/version: LineageOS 20.0 (20-20230701-microG-a52q)

**Logs**
{
  "apkCertificateDigestSha256": [
    "CFMi+R9OCRrIqon0WdOwQgA4I9aG0m1sYPZuUf5a2ns="
  ],
  "apkDigestSha256": "6eSwd6Ed+f4Pab9sXTvk+hqbA8VFtfdCnYlznf+zIbc=",
  "apkPackageName": "rikka.safetynetchecker",
  "basicIntegrity": true,
  "ctsProfileMatch": false,
  "evaluationType": "BASIC,HARDWARE_BACKED",
  "nonce": "YmY2ZjAwNGYtNDkxNC00MTc4LWI0ZmYtMDA4NDNhZTk1MGZlCjIwMjMtMDctMDdUMTQ6MTI6MzQuOTM2KzAyOjAwCnNhbXN1bmcvYTUycW5zeHgvYTUycToxMy9UUTNBLjIzMDYwNS4wMTIvZW5nLnJvb3QuMjAyMzA3MDEuMDAzMTU3OnVzZXIvcmVsZWFzZS1rZXlzCjMzCjIwMjMtMDYtMDUK",
  "timestampMs": 1688731961998,
  "deprecationInformation": "The SafetyNet Attestation API is deprecated. It is recommended to use the Play Integrity API: https://g.co/play/safetynet-timeline."
}

**Additional context**
If have got the MagiskHide Props config module with the fingerprint of my phone (like you're using it without root). I have tried it without: the only difference was that it fails with the CTS profile with the BASIC evaluation type. It likely doesn't matter, but I'm just telling you to be sure

**Checklist**
- [Y ] All information is present
- [Y] Logs are attached
- [Y ] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by Jon8RFC** [comment]
In my experience, if safetynetfix is not reinstalled quickly enough, it will fail and keep that stored.

I like to enable airplane mode, force close google play store & clear data, force close google play services & clear data, and do both of them very quickly within one another, at least twice each, then restart.  Usually multiple clears does it, but a single clear of each sometimes won't.

That typically resolves it for me, unless there's another magisk module or xposed/lsposed module causing the issue.  That cannot be properly ruled out without disabling all of them, restarting, THEN clearing play store & play services data and restarting a second time.

Have you tried the above as well as Displax's safetynetfix-mod?
https://github.com/Displax/safetynet-fix/releases

**Comment by XanderTheDev** [comment]
> In my experience, if safetynetfix is not reinstalled quickly enough, it will fail and keep that stored.
> 
> I like to enable airplane mode, force close google play store & clear data, force close google play services & clear data, and do both of them very quickly within one another, at least twice each, then restart. Usually multiple clears does it, but a single clear of each sometimes won't.
> 
> That typically resolves it for me, unless there's another magisk module or xposed/lsposed module causing the issue. That cannot be properly ruled out without disabling all of them, restarting, THEN clearing play store & play services data and restarting a second time.
> 
> Have you tried the above as well as Displax's safetynetfix-mod? https://github.com/Displax/safetynet-fix/releases

Thanks! I tried to install the mod from Display (the microg version) and it works now!

Photo:
![Screenshot_20230708-194010_Yet Another SafetyNet Attestation Checker](https://github.com/kdrag0n/safetynet-fix/assets/101188151/d7719715-85ca-4d35-955f-bc6d71ada73b)
