### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by dxdvostfr** [kdrag0n/safetynet-fix#293]
[deleted]

**Comment by Jon8RFC** [comment]
Have you tried Displax's safetynetfix-mod?
https://github.com/Displax/safetynet-fix/releases
(use mod 1.3 if 2.0 doesn't work)

In my experience, if safetynetfix is not reinstalled quickly enough, Play Store certification will fail and might keep that stored. But Displax's mod may resolve the safetynet failures. 

For the Play Store certification, I enable airplane mode, force close google play store & clear data, force close google play services & clear data, and do both of them very quickly within one another, at least twice each, then restart.  Usually multiple clears does it, but a single clear of each sometimes won't.

That typically resolves that part for me, unless there's another magisk module or xposed/lsposed module causing the issue.  That cannot be properly ruled out without disabling all of them, restarting, THEN clearing play store & play services data and restarting a second time.

**Comment by linux019** [comment]
Yasnac and safety net are deprecated. They replaced with Play Integrity. You have to disable hardware-backed attestation that is possible only with mods or OS that fakes OS version that doesn't support hw attestation

**Comment by ATa0ist** [comment]
> safetynetfix-mod

only needs Displax's safetynetfix-mod,
 or both this and safetynetfix-mod?

**Comment by Jon8RFC** [comment]
Only Displax's module.  If 2.0 doesn't work, use 1.3

Here's a (THE?) play integrity checker everyone is using:
https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck

**Comment by ATa0ist** [comment]
> Only Displax's module. It was very recently updated again with a major improvement.
> 
> Here's a (THE?) play integrity checker everyone is using: https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck

thank you. it worked！

**Comment by SurajBehera23** [comment]
All the above methods didn't work for me. I am on 1.5.6 tried the above mentioned module but only basic integrity passed for me. can anyone help or suggest anything please.

**Comment by Jon8RFC** [comment]
> All the above methods didn't work for me. I am on 1.5.6 tried the above mentioned module but only basic integrity passed for me. can anyone help or suggest anything please.

Do you have no other magisk modules installed, no xposed/lspoed/other-posed things installed, and selinux is enforcing rather than permissive?  Beyond trying all of that to rule something else out, I'm no more help.

Apparently selinux permissive causes failures, and I've had magisk modules and lsposed modules cause failures as well.

If you can find which of those is the culprit, either that module can be corrected for the newer version of android you're running, or maybe a workaround can be found by someone with safetynetfix.

**Comment by shhahid7** [comment]
> Only Displax's module. It was very recently updated again with a major improvement.
> 
> Here's a (THE?) play integrity checker everyone is using: https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck

Thanks its worked, flawlessly, thanks for updating!!!
