### ISSUE TITLE
Phone soft reboots after applying fix.

### ISSUE THREAD

**Issue by Aholicknight** [kdrag0n/safetynet-fix#3]
**This isn't really an issue** but when I apply the fix onto my phone and restart, the phone restarts again (shows boot screen), then it works fine shortly after. Why does this happen?

**Comment by UltraTV** [comment]
I'd like to add, that I found out this is especially happening on many samsung devices, including the A-Series (Android 9-10)

**Comment by Aholicknight** [comment]
@UltraTV My phone is not a skinned ROM, just stock android with magisk root.

**Comment by QkiZMR** [comment]
Maybe catch logcat and paste here.

**Comment by kdrag0n** [comment]
Please test the new solution in #13 and continue discussion there.

**Comment by Aholicknight** [comment]
This appears to fix the problem that I was having. Thanks!
