### ISSUE TITLE
Device not certified.

### ISSUE THREAD

**Issue by SalvatoreNoschese** [kdrag0n/safetynet-fix#300]
After November update in my pixel 7 pro, safety net seems to be ok but device is no more certified.
![Screenshot_20231116-154433](https://github.com/kdrag0n/safetynet-fix/assets/16841896/656f4605-dc7a-4f97-b4b0-ad4de2783309)
![Screenshot_20231116-154438](https://github.com/kdrag0n/safetynet-fix/assets/16841896/b814f5b6-f316-465b-9bd3-3414687f868a)

**Comment by fastleo63** [comment]
Me, too. POCO F3, MIUI Global 14.0.9, Magisk 26.4. Maybe Google made some changes, yesterday device was still certified.

**Comment by Jon8RFC** [comment]
This should work:
https://github.com/chiteroman/PlayIntegrityFix/releases

**Comment by anko20094** [comment]
> This should work:
> https://github.com/chiteroman/PlayIntegrityFix/releases

That helped for pixel 7(13 android), thanks a lot!

**Comment by SalvatoreNoschese** [comment]
> This should work: https://github.com/chiteroman/PlayIntegrityFix/releases

TYSM. Now is again certified 😃
