### ISSUE TITLE
Seems to brake fingerprint functionality

### ISSUE THREAD

**Issue by dibg** [kdrag0n/safetynet-fix#31]
Seems to brake fingerprint functionality on my s10e with android 10.
I do pass safetynet with this, but the applications depend on the fingerprint throw errors or crash. Unlocking the phone with fingerprint is not affected.
Disabling it the applications work again and i pass basic integrity but fail on cts.

Keepass2offline:
![image](https://user-images.githubusercontent.com/15279833/112093994-16009880-8ba3-11eb-87bb-90c988524d28.png)

**Comment by kdrag0n** [comment]
This is the same underlying issue as #32.
