### ISSUE TITLE
Support for heavily-customized OEM ROMs (e.g. One UI, MIUI)

### ISSUE THREAD

**Issue by kdrag0n** [kdrag0n/safetynet-fix#32]
## For users

Universal SafetyNet Fix is not compatible with heavy OEM skins such as Samsung One UI and MIUI. You can try it at your own risk, but don't expect it to work. Instability and/or bootloops are likely. **Common issues include broken fingerprint unlocking, broken biometric authentication in apps, crashing apps, and more.**

### DO NOT report issues if you are using a heavy OEM skin.

---

## For developers

Replacing the keystore service causes breakage on heavily-customized OEM ROMs where the vendor has made intrusive changes that don't work with the AOSP keystore service. The most prominent example of this is Samsung One UI, but there are other vendors doing this.

Patching the keystore service executable is not a scalable solution, so this needs to be fixed another way. The current proposal is to shim the system's existing service (#13, blocked by #33), but I'm open to other ideas.

Feel free to propose alternative ideas or submit an implementation PR.

**Comment by KHOENIX** [comment]
#31

**Comment by KHOENIX** [comment]
#41

**Comment by KHOENIX** [comment]
#43

**Comment by KHOENIX** [comment]
#40

**Comment by KHOENIX** [comment]
> Replacing the keystore service causes breakage on heavily-customized OEM ROMs where the vendor has made intrusive changes that don't work with the AOSP keystore service. The most prominent example of this is Samsung One UI, but there are other vendors doing this.
> 
> Patching the keystore service executable is not a scalable solution, so this needs to be fixed another way. The current proposal is to shim the system's existing service (#13, blocked by #33), but I'm open to other ideas.
> 
> Feel free to propose alternative ideas or submit an implementation PR.

**Comment by NitroVenom** [comment]
Pro dev I can test. I have miui

**Comment by kdrag0n** [comment]
Support for heavy OEM skins has been added in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).
