### ISSUE TITLE
safetynet-fix v1.1.1: Bootloop on LineageOS 18.1

### ISSUE THREAD

**Issue by Caio99BR** [kdrag0n/safetynet-fix#35]
After upgrade from LineageOS17.1 to 18.1 the system bootloop, I dont know what log I should upload to help solve this issue (Im not familiar with this anymore, please help)

_MagiskHide Props is working too (SafetyNet sucess), but I dont remeber why I'm using this too_

**Comment by toryas** [comment]
I have the same problem in Galaxy S20 with Andoird 10

**Comment by kdrag0n** [comment]
@Caio99BR You need to reinstall the module after upgrading to a new major Android version.

@toryas That's an unrelated issue, see #32.
