### ISSUE TITLE
Help on framework version of the workaround (Android 11)

### ISSUE THREAD

**Issue by psychopathologist** [kdrag0n/safetynet-fix#4]
First of all thank you so much for the fix. You're insane!

I've hooked the attestKey method and printed all the outputs from mContext.getPackageName(), but I didn't receive "com.google.android.gms" string at any time (but other packages). Any clue?

Thanks in advance.

**Comment by kdrag0n** [comment]
If you're actually getting hardware attestation and performing a SafetyNet test while checking it, GMS will show up there. If not, it's not actually using hardware attestation.

**Comment by psychopathologist** [comment]
> If you're actually getting hardware attestation and performing a SafetyNet test while checking it, GMS will show up there. If not, it's not actually using hardware attestation.
Thank you!
Nevermind, EdXposed Manager was preventing "com.google.android.gms" to be hooked in (Pass SafetyNet / App List mode features). After disabling both mentioned features, hook gets installed in the method and the workaround finally worked (got evalType = BASIC). I guess I still need the props in your magisk module, right?

**Comment by kdrag0n** [comment]
Yes, you still need a variety of properties (depending on device) to pass basic attestation. Check MagiskHide for a more complete list of properties.
