### ISSUE TITLE
Nexus 7 2013: Unsupported CPU architecture: armeabi-v7a

### ISSUE THREAD

**Issue by djibe** [kdrag0n/safetynet-fix#44]
Hi,

When trying to flash safetynet-fix from Magisk, I get this error: Nexus 7 2013: Unsupported CPU architecture: armeabi-v7a

How could we compile for Nexus 7 2013 ?
Thanks a lot

**Comment by Didgeridoohan** [comment]
That's an ancient device. It does not have the hardware that this module circumvents... You don't need it.
