### ISSUE TITLE
CPU architecture support

### ISSUE THREAD

**Issue by hieppo** [kdrag0n/safetynet-fix#5]
What CPU does the zip file support?
I am trying to install on an ARM v7a 32bit platform? 32bit Lineage OS was the only one available for the Fire HD8 tablet. Let me know if there is any chance for compile version to support this CPU.

**Comment by kdrag0n** [comment]
Only 64-bit ARM (ARMv8 AArch64) is supported. It's possible to support 32-bit ARM, but I'm not aware of any 32-bit ARM devices supporting hardware attestation. Failing SafetyNet on a 32-bit device is very unlikely to be caused by hardware attestation.

**Comment by hieppo** [comment]
ok, I guess this fix would not fix the issue with my 32bit ARM. I guess it is something else since SafetyNet test failed. I look some more
