### ISSUE TITLE
Support for Android 12

### ISSUE THREAD

**Issue by Aluminite** [kdrag0n/safetynet-fix#52]
I'm using a Pixel 3a XL. When this module is installed and I try to put in my pattern, the screen goes black for a few seconds and I get kicked back to the lock screen. Everything works normally if I remove the module.

[logcat.txt](https://github.com/kdrag0n/safetynet-fix/files/6509366/logcat.txt)

**Comment by kdrag0n** [comment]
I'm unlikely to consider supporting Android 12 until it's stable, but I'll leave this issue open for reference.

**Comment by romanze87** [comment]
Same with me. Pixel 3 Android 12, once hitting Reboot phone goes to unlock screen, I enter my pattern, screen flashes black then goes right back to unlock screen.

**Comment by kdrag0n** [comment]
Android 12 Beta 2 is now supported in v1.2.0. Please note that this will likely be fragile until Android 12 is stable, i.e. the module will need to be updated for each Android 12 build, so don't expect v1.2.0 to keep working on Beta 3.
