### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by maxkraft7** [kdrag0n/safetynet-fix#54]
On my oneplus nord when I check for saftetynet in magisk it does nothing for a long time and then it says eval type n/a. I assume there is some kind of timeout and there is just no response coming back. I see similar effects in my banking app. There used to be a error saying "Your phone is rooted, this app can't be used". Now it's just stuck at the start-sequence. I assume it's waiting for some kind of safetyNet response. Would it be possible to mock a positive response? I think then it should work.

**Comment by kdrag0n** [comment]
Getting evalType N/A has nothing to do with Universal SafetyNet Fix. Update Magisk or check your other modifications for the culprit.
