### ISSUE TITLE
Support for Android 7.1.2

### ISSUE THREAD

**Issue by weaverlave** [kdrag0n/safetynet-fix#55]
A lot of industrial Android Devices does have Android 7.1.2. Could you please add support?

**Comment by kdrag0n** [comment]
Can you give an example of an Android 7 device that supports hardware-backed key attestation?

**Comment by kdrag0n** [comment]
Support for Android 7.x has been added in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).

**Comment by JakoDel** [comment]
> Support for Android 7.x has been added in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).

Sorry for the necro, just wanted to ask two questions (thanks a lot for your work btw!)
1.) why was support for 7 removed so quickly? 2)do you think 2.2.0 (which I think is the last version with 7 support) would still work?
