### ISSUE TITLE
SafetyNet Fails

### ISSUE THREAD

**Issue by alisyed25** [kdrag0n/safetynet-fix#56]
May security update Safety Net ctsProfile fails. Android 10 and Android 11

**Comment by Conan179** [comment]
Which device? Which Roms? I cannot confirm it with my note 20 and dr.ketan rom, saftynet pass.

**Comment by alisyed25** [comment]
S20, S20 ulta samsung tab 6. If you update to the any firmware release mid May ctsprofile fails. On S20 ulta if I go back to April firmware it passes

**Comment by kdrag0n** [comment]
This has nothing to do with Universal SafetyNet Fix.

**Comment by alisyed25** [comment]
It should because this fix no longer works
