### ISSUE TITLE
building libraries confusion

### ISSUE THREAD

**Issue by mcdoe** [kdrag0n/safetynet-fix#61]
Hi, trying to build the shim library- can you point me in the right direction? I'm new to soong. Did you build this under a larger project? #33

**Comment by kdrag0n** [comment]
Yes, Soong can only be used to build this as a part of a custom ROM. Add vendor/keystore_shim to an AOSP tree and build with `m libkeystore_shim` after running `lunch` with a generic AOSP device tree. Help with the AOSP build system is out-of-scope for this repo.

**Comment by mcdoe** [comment]
wait, I'm not a custom rom dev. Can you just tell me how to add to the tree? Everything else I get.
