### ISSUE TITLE
Any way to revert the zip flash on TWRP?

### ISSUE THREAD

**Issue by ragymorkos** [kdrag0n/safetynet-fix#64]
Using OnePlus 6 stock ROM with OxygenOS version 10.3.11.

I tried flashing the v1.1.1 zip file in TWRP, but it caused a bootloop. This was fixed afterwards within TWRP (in TWRP's advanced options, there is an option to fix bootloop issues, and just running that fixes the issue). However, it also removes the Magisk root, and if I try to flash Magisk again in TWRP, the bootloop issue happens again and I have to use the fix mentioned above, which again removes Magisk.

As the title mentions, any way to revert the safetynet-fix zip flash on TWRP?

**Comment by kdrag0n** [comment]
You can use Safe Mode: https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help

**Comment by ragymorkos** [comment]
> You can use Safe Mode: https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help

The link is about ADB and Magsik, but like I mentioned, I can't even boot into the device or use ADB, so cannot use this.

Can my issue be kept open since I can't seem to solve it? And I'll update here if I manage to find a solution.

**Comment by ragymorkos** [comment]
@kdrag0n ok, I've managed to fix the issue! I basically did the following:

1. Boot to TWRP and uninstall Magisk with the [steps here](https://topjohnwu.github.io/Magisk/install.html#uninstallation), then boot to system
2. Boot to TWRP and install Magisk
3. Boot from step 2 directly to TWRP, not the system (not sure if this step was necessary, but read on multiple posts on XDA that it made a difference)
4. Boot from step 3 to system

Hope that helps someone out who has faced the same issue!

**Comment by Didgeridoohan** [comment]
> @kdrag0n ok, I've managed to fix the issue! I basically did the following:
> 
> 1. Boot to TWRP and uninstall Magisk with the [steps here](https://topjohnwu.github.io/Magisk/install.html#uninstallation), then boot to system
> 2. Boot to TWRP and install Magisk
> 3. Boot from step 2 directly to TWRP, not the system (not sure if this step was necessary, but read on multiple posts on XDA that it made a difference)
> 4. Boot from step 3 to system
> 
> Hope that helps someone out who has faced the same issue!

Quite unnecessary... If the ADB command doesn't work (you don't have to be booted into Android for the command to work though, it's designed to work during a bootloop) you can simply navigate to /data/adb/modules in the TWRP file manager and remove the module from there.

**Comment by crok** [comment]
> ..you can simply navigate to /data/adb/modules in the TWRP file manager and remove the module from there.

I prefer to create a `disable` (or even a `remove`) file to trigger Magisk itself to deal with the module when booting the system. But, as always, you are basically right, the method I used to use differs only by triggering the "native" Magisk procedures to disable / delete the module's files and call the uninstall script to clean up residues, etc.. the effect is more or less >98% the same anyway.

@ragymorkos the universal way of this is:
Boot to TWRP and start a shell _(it will start a root shell, no need for su)_:
`ls -al /data/adb`
check the dirnames, pick your module's name and
to disable the module issue the command:
`touch /data/adb/[insert your module's name]/disable`
or to remove the module completely issue the command:
`touch /data/adb/[insert your module's name]/remove`

Same method but less typing - tailored for this module:
to disable the module issue the command:
`touch /data/adb/safetynet-fix/disable`
or to remove the module completely issue the command:
`touch /data/adb/safetynet-fix/remove`

Hope you get the idea now..
..and reboot the device.

**Comment by Didgeridoohan** [comment]
@crok That is the preferred way, generally, but not really necessary for this module. But there's no need to work with adb, the TWRP file manager is enough.

Navigate to /data/adb/modules, open the directory for the module in question and rename `module.prop` to `disable` or `remove` respectively. If you later want to enable the module again (if you've just disabled it) you just rename the file back up `module.prop` again. A lot less typing and no computer required...

**Comment by crok** [comment]
> and no computer required...

Indeed, non of the methods needs PC or anything.
