### ISSUE TITLE
Boot loop after system upgrade (Pixel 3, Android 10 to 11)

### ISSUE THREAD

**Issue by pingu8007** [kdrag0n/safetynet-fix#65]
I upgrade my Google Pixel 3 (blueline) to Android 11 yesterday. Once completed I found every time I enable safetynet-fix, the phone fail into boot loop.

Full reset MagiskHide Props doesn't help, and it doesn't cause boot loop, neither.

The problem solved after I reinstall this module, and I noticed the message say something like `Install for Android 11`.
Does this mean there are something been determined during module install rather than boot time? Is it required to remove module before any huge system upgrade, e.g. the coming Android 11 to 12?

**Comment by kdrag0n** [comment]
Yes, the module checks the Android version once at install time. It should be easy to make that dynamic though, so I'll revisit this when 12 rolls around.

Keep in mind that Android 12 will not supported at launch. I work on SafetyNet as part of my ProtonAOSP custom ROM project, so you'll need to wait for ProtonAOSP 12 before expecting an update for it.

**Comment by kdrag0n** [comment]
Fixed in 7a732dc9e224fc0d806e6f1266c5475925b8f9ab.
