### ISSUE TITLE
Can the module survive factory reset ?

### ISSUE THREAD

**Issue by Kojuda** [kdrag0n/safetynet-fix#66]
Hello,

I was wondering whether there is a way the module survives factory reset ? Or can it be modified to do so ? I am in a situation where I only need to bypass SafetyNet from the initial setup without being able to upgrade Magisk or access the developers options before the test.

Thanks for reading.

**Comment by pndwal** [comment]
No!

This wipes data! - Magisk modules are stored at /data/ADB

Please read Magisk documentation, and close this non-issue. 😜 PW

**Comment by Kojuda** [comment]
Thank you, but you have completely missed the real question : "finding a way to install the module before the initial question"

To respond to the question for those in a similar context => Reset factory => Modify build.prop and persist.sys.usb.config from TWRP to enable USB Debugging manually => ADB install Magisk from the setup => use magisk cli to install SafetyNet Fix => Bypass the SatetyNet check of a MDM activation.
