### ISSUE TITLE
armv7-a devices not supported

### ISSUE THREAD

**Issue by weirdal3333** [kdrag0n/safetynet-fix#7]
Many armv7-a devices (motorola devices especially) that have low-end processors.
Is there any way to make a multi-platform installer that covers every build? I wouldn't think that you'd need to compile the entire firmware for every device, just the keystore file (with the patches). 

The build could detect which cpu you have like it does now, but with a for loop (magisk does this).

**Comment by tygger** [comment]
Same issue here... failing basic CTS Profile and cannot install the Safetynet-Fix module. Getting this error message: unsupported cpu architecture: armeabi-v7a.

**Comment by kdrag0n** [comment]
Do you have any specific examples of such devices that support hardware attestation? I can support 32-bit ARMv7, but I haven't seen any 32-bit devices new enough for hardware attestation. You can use the Key Attestation Demo app to check.

**Comment by tygger** [comment]
Magisk shows evalType is Basic, but here's the Attestation Demo app screenshot. 
![Screenshot_20210121-164108](https://user-images.githubusercontent.com/27453102/105416296-e9aeb700-5c07-11eb-989c-191e5f3c9885.png)

**Comment by weirdal3333** [comment]
I am going to go out on a limb here and guess that this is an issue because Motorola.
![Screenshot_20210122-000321](https://user-images.githubusercontent.com/3537180/105448937-4aa8b000-5c45-11eb-9515-d46d0ac587d5.png)
![Screenshot_20210122-000318](https://user-images.githubusercontent.com/3537180/105448938-4b414680-5c45-11eb-97aa-2d62226b2bb7.png)
![Screenshot_20210122-000046](https://user-images.githubusercontent.com/3537180/105448940-4bd9dd00-5c45-11eb-9a26-2f67f51268ca.png)

**Comment by weirdal3333** [comment]
Would it be easy to only port the problematic library instead of the entire device build for every type of cpu?
A script could check the props files for certain strings and change them to the correct values/add the right lines, as well.
Updates would be small and you could do semi-silent build updates to fix relevant devices, until everything works for everyone, without huge changes or extra compile time.
I would be willing to test an arm7a build on my 2018 Moto e5 xt1920dl tracphone edition device. It's a weird device with no support, but has had all the issues that other similar devices currently have. If something goes wrong, I have backups of everything! I've had to directly edit the fstab to fix the partition mounting in unencrypted mode in a certain order to make magisk and twrp actually work.
If it doesn't fix it, something else is causing safetynet to fail on all Motorola devices. My play store is still certified, so it could just be Motorola being Motorola.

**Comment by Praxtical** [comment]
My sm-t510 is giving the same error, would it be easy to add armabi-v7a? If not then I'll just deal with it lol

**Comment by Praxtical** [comment]
> Do you have any specific examples of such devices that support hardware attestation? I can support 32-bit ARMv7, but I haven't seen any 32-bit devices new enough for hardware attestation. You can use the Key Attestation Demo app to check.

Yea, I have a 2019 Samsung Galaxy Tab A 10.1 WiFi. I have hardware attestation, with 32-bit ARMv7. There may not be many phones, but it will prevent questions like this in the future.

**Comment by kdrag0n** [comment]
Please test the new solution in #13 and continue discussion there.
