### ISSUE TITLE
Porting to arm7 32bit

### ISSUE THREAD

**Issue by Praxtical** [kdrag0n/safetynet-fix#70]
My device was formed in the depths of hell with the worst attributes possible. I have a very sensitive samsung tab, with an arm7 chip, and it doesn't work with the shim method. Great! Was wondering if I could just recompile on my device so arm7 works with the 1.2.0 changes. Is there anything I have to change before compiling so it accepts it?

**Comment by Praxtical** [comment]
also the 1.0.0 version that has compatibility for arm7 bootloops my device, so im hoping to compile the later versions

**Comment by remustata** [comment]
+1 as I also experience a similar issue on my sony z3c phone:
Unsupported CPU architecture: armeabi-v7a
! Installation failed

**Comment by mariuszsz87** [comment]
+1
I have the same issue on HTC One M8 - "Unsupported CPU architecture: armeabi-v7a".

**Comment by Praxtical** [comment]
Have you guys tried shim?

**Comment by kdrag0n** [comment]
No changes should be necessary for ARMv7. The patches are architecture-agnostic, so you can apply them to AOSP and compile keystore for ARMv7.
