### ISSUE TITLE
Android 12 beta 3 won't pass check

### ISSUE THREAD

**Issue by Vegas7** [kdrag0n/safetynet-fix#71]

**Comment by KGB333** [comment]
![Screenshot_20210715-193702.png](https://user-images.githubusercontent.com/35756327/125782026-d1874c16-857f-48e7-88ca-b73d17c8c8c4.png)

**Comment by BlazeCodeDev** [comment]
Same error here

**Comment by vaugerbird** [comment]
Adding to the same chain

**Comment by kkazakov** [comment]
I've copied (in the zip) 

system_sdk31-b2 to system_sdk31 and now it works.

**Comment by BlazeCodeDev** [comment]
Can confirm that the installation works like this, but my ctsProfile still reports false. Not sure if it has something to do with it.

**Comment by kkazakov** [comment]
Yes, true. Perhaps there's something else. ctsProfile reports false, here too.

**Comment by guoyanhuyun** [comment]
same error +1

**Comment by kkazakov** [comment]
ctsProfile reports false, bug Google Pay works ... go figure.

**Comment by Jolanrensen** [comment]
@kkazakov Google pay even works with version 1.1.1 of the safetynet fix on beta 3. CTS also fails

**Comment by BlazeCodeDev** [comment]
GPay works for me too, but all PayPal seems to be crashing on start and my banking apps still recognize root, magisk hide is enabled.

**Comment by bleez99** [comment]
It works completely...
Beta 3: the SDK is out of beta.  It's just 31.
So, before an official fix, crack open the zip:
1. Rename the directory system_sdk31-b2 to system_sdk31
2. Fix up customize.sh
3. Fix up service.sh
Install and have a safetynet pass.

Change to customize.sh:
`sdk="$(getprop ro.build.version.sdk)"
version="$(getprop ro.vendor.build.version.release)"
if getprop ro.build.id | grep -q SPB3; then
    sdk=31
    version="12 Beta 3"
fi`

Change to service.sh:
`sdk="$(getprop ro.build.version.sdk)"
version="$(getprop ro.vendor.build.version.release)"
if getprop ro.build.id | grep -q SPB3; then
    sdk=31
    version="12 Beta 3"
fi`

**Comment by BlazeCodeDev** [comment]
- [x] Unfortunately doesn't install for me. ![Screenshot_20210718-015657.png](https://user-images.githubusercontent.com/60486125/126051838-081fdf09-fd52-44a5-9c9f-2263fe0eced2.png)

![Screenshot_20210718-015710.png](https://user-images.githubusercontent.com/60486125/126051839-7782bd2b-4e2a-46ef-bef9-7c1155e2b172.png)

**Comment by bleez99** [comment]
Syntax error. If you want I can post the zip file and you can examine my changes. 

On July 17, 2021 7:58:06 PM Ralf Lehmann ***@***.***> wrote:


*	 Unfortunately doesn't install for me. <https://user-images.githubusercontent.com/60486125/126051838-081fdf09-fd52-44a5-9c9f-2263fe0eced2.png> 

 <https://user-images.githubusercontent.com/60486125/126051839-7782bd2b-4e2a-46ef-bef9-7c1155e2b172.png>

**Comment by KGB333** [comment]
> It works completely with a little help.
> 
> Beta 3: the SDK is out of beta.  It's just 31.
> So, before an official fix, crack open the zip:
> 1. Rename the directory system_sdk31-b2 to system_sdk31
> 2. Fix up customize.sh
> 3. Fix up service.sh
> Install and have a safetynet pass.
> 
> Change to customize.sh:
> `sdk="$(getprop ro.build.version.sdk)"
> version="$(getprop ro.vendor.build.version.release)"
> if getprop ro.build.id | grep -q SPB3; then
>     sdk=31
>     version="12 Beta 3"
> fi`
> 
> Change to service.sh:
> `if getprop ro.build.id | grep -q SPB3; then`
> 
> This is a moving target...
> 
> ![Screenshot_20210717-192000](https://user-images.githubusercontent.com/3842064/126051389-4f08b2f3-0876-4fc4-8ed7-9b477b7f8209.png)
> 

Thanks man, This method works for my Pxiel on Beta 3
![Screenshot_20210718-145230.png](https://user-images.githubusercontent.com/35756327/126058488-31eb888f-df37-46e0-960a-4f0ba9be234d.png)

**Comment by BlazeCodeDev** [comment]
Thanks for the offer @bleez99. It works now. Turns out editing the files on your phone doesnt work. I now tried it on my PC using Notepad++ and it works. ctsProfile passes! Thank you very much

**Comment by pax2011** [comment]
> It works completely with a little help.
> 
> Beta 3: the SDK is out of beta. It's just 31.
> So, before an official fix, crack open the zip:
> 
> 1. Rename the directory system_sdk31-b2 to system_sdk31
> 2. Fix up customize.sh
> 3. Fix up service.sh
>    Install and have a safetynet pass.
> 
> Change to customize.sh:
> `sdk="$(getprop ro.build.version.sdk)" version="$(getprop ro.vendor.build.version.release)" if getprop ro.build.id | grep -q SPB3; then sdk=31 version="12 Beta 3" fi`
> 
> Change to service.sh:
> `if getprop ro.build.id | grep -q SPB3; then`
> 
> This is a moving target...
> 
> ![Screenshot_20210717-192000](https://user-images.githubusercontent.com/3842064/126051389-4f08b2f3-0876-4fc4-8ed7-9b477b7f8209.png)

Can you share the zip?

**Comment by BlazeCodeDev** [comment]
> Can you share the zip?

Here is mine, did the same changes.
[safetynet-fix-1.2.0.zip](https://github.com/kdrag0n/safetynet-fix/files/6836049/safetynet-fix-1.2.0.zip)

**Comment by pax2011** [comment]
> > Can you share the zip?
> 
> Here is mine, did the same changes.
> [safetynet-fix-1.2.0.zip](https://github.com/kdrag0n/safetynet-fix/files/6836049/safetynet-fix-1.2.0.zip)

![telegram-cloud-photo-size-4-6026314870271620246-y](https://user-images.githubusercontent.com/56022493/126070222-f4d68b91-2c91-4f3e-9609-06b49126e6b2.jpg)

**Comment by BlazeCodeDev** [comment]
> > > Can you share the zip?
> > 
> > 
> > Here is mine, did the same changes.
> > [safetynet-fix-1.2.0.zip](https://github.com/kdrag0n/safetynet-fix/files/6836049/safetynet-fix-1.2.0.zip)
> 
> ![telegram-cloud-photo-size-4-6026314870271620246-y](https://user-images.githubusercontent.com/56022493/126070222-f4d68b91-2c91-4f3e-9609-06b49126e6b2.jpg)

Thats odd mine installed right away...

**Comment by bleez99** [comment]
I apologize for not posting diffs, but I see you have the required changes posted and working.
Until 12 is out of beta, adjustments will most likely be needed again.  The good news is that the binaries already built seem compatible with the beta, and all we need to do is string match the properties returned in the two shell scripts in the zip.
I do highly recommend not doing this on the phone, use good tools and do the zip changes on your PC, in my case Linux, Ark, and Kate.  Open, edit, and save back to the zip file.

**Comment by Jolanrensen** [comment]
> It works completely with a little help.
> 
> Beta 3: the SDK is out of beta. It's just 31.
> So, before an official fix, crack open the zip:
> 
> 1. Rename the directory system_sdk31-b2 to system_sdk31
> 2. Fix up customize.sh
> 3. Fix up service.sh
>    Install and have a safetynet pass.
> 
> Change to customize.sh:
> `sdk="$(getprop ro.build.version.sdk)" version="$(getprop ro.vendor.build.version.release)" if getprop ro.build.id | grep -q SPB3; then sdk=31 version="12 Beta 3" fi`
> 
> Change to service.sh:
> `if getprop ro.build.id | grep -q SPB3; then`
> 
> This is a moving target...
> 
> ![Screenshot_20210717-192000](https://user-images.githubusercontent.com/3842064/126051389-4f08b2f3-0876-4fc4-8ed7-9b477b7f8209.png)

Consider making a pull request with your changes, I'm sure @kdrag0n will appreciate having a working version (unless it somehow breaks something)

**Comment by bleez99** [comment]
Pull request committed

**Comment by kdrag0n** [comment]
Superseded by #76.
