### ISSUE TITLE
Android 12 Beta 4 SafetyNet check doesn't pass

### ISSUE THREAD

**Issue by BlazeCodeDev** [kdrag0n/safetynet-fix#76]

**Comment by RodertHaung** [comment]
I tried and keeps crushing at lockscreen, and shows Bluetooth stop working.

**Comment by BlazeCodeDev** [comment]
I tried it the way it was done in #71, but my phone decided to boot loop after installing it.

**Comment by donnyblack** [comment]
Here's a zip that will install successfully but **will not fix a failing SafetyNet ctsProfile**. 

However, I highly encourage you to create your own file instead by following these steps:

1. Download the latest safetynet-fix zip
2. Use winrar to open the file
3. In winrar, extract the service.sh and customize.sh files
4. In Notepad++, open both files and make the exact modifications described in #71 (you can check your work by viewing the versions of those files that are in my attached zip)
5. In winrar, right-click the service.sh and customize.sh files and delete them
6. Finally, right click anywhere within the winrar window, select "Add files to archive", and add the newly updated service.sh and customize.sh files.

Device tested: Pixel 5
[safetynet-fix-v1.2.0.zip](https://github.com/kdrag0n/safetynet-fix/files/7024630/safetynet-fix-v1.2.0.zip)

**Comment by kdrag0n** [comment]
It will install successfully, but service.sh is essential for the module to work on Android 12. It won't do anything if you delete that file.

**Comment by donnyblack** [comment]
It's not removed though, it's replaced. In my attached zip file, you can
see it's there.

**Comment by Jolanrensen** [comment]
@kdrag0n so say I build the aosp_arm64 from the master source, is it then simply a copy-paste of those two files or is there something else that needs to be done?

**Comment by kdrag0n** [comment]
Support for Android 12 Beta 4, as well as future versions, has been added in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).
