### ISSUE TITLE
What version does Riru support?

### ISSUE THREAD

**Issue by cracky5322** [kdrag0n/safetynet-fix#83]
The current version of Riru supported by Lsposed and EDXposed is not the same.
I would like to ask you the lowest version of Riru currently supported?

Riru v26+ has removed v24 support
Lsposed support v26+
EDXposed only supports v25

**Comment by steven7851** [comment]
You can refer [here](https://github.com/kdrag0n/safetynet-fix/blob/master/riru/module.gradle).

**Comment by kdrag0n** [comment]
This module should support v24 and newer. I've been testing it with v26.
