### ISSUE TITLE
Safteynet not bypassed one ui

### ISSUE THREAD

**Issue by b1ackfa1c0n** [kdrag0n/safetynet-fix#84]
Safteynet not bypassed on samsung sm-a605f android 10 one ui 2.0,
older version of this module caused boot loop, now it doesn't cause a boot loop, but unfortunately it doesn't bypass safteynet, so anyone have an idea what's wrong, is it something I have done or what ?

**Comment by Dydnlee** [comment]
2.1.0 ı yükleyin

**Comment by b1ackfa1c0n** [comment]
> Install version 2.1.0. also install riru module
Excuse me, but I can't find version 2.1.0, I installed riru core module from magisk.

**Comment by Dydnlee** [comment]
paid 

https://patreon.kdrag0n.dev/buy/exclusive/safetynet-fix-v2.1.0.zip
