### ISSUE TITLE
Redmi Note 9 Pro MIUI 12.0.4 Global ctsProfile false

### ISSUE THREAD

**Issue by mistergoliath41** [kdrag0n/safetynet-fix#85]
![Screenshot_2021-09-07-18-59-37-871_hcaz dg](https://user-images.githubusercontent.com/37485357/132383538-90654072-29ea-433e-9bf1-2a8196e52881.jpg)

**Comment by mistergoliath41** [comment]
My bad, i seen that it was needed to block the GMS tracking in XPrivacyLua but i thought i only had to check the GMS on LSPosed > Modules > XPrivacyLua.
I followed this tuto: https://m.youtube.com/watch?v=I9A3yxAi-Ww
And now ctsProfile is not failing anymore:
![Screenshot_2021-09-07-19-46-35-226_f vpsa sjkxlfxjtaq](https://user-images.githubusercontent.com/37485357/132388609-ba14c716-3015-4e10-ad06-5ee170ee1df2.jpg)

**Comment by softgrass** [comment]
The above method works for the Pixel 4a 5G on Android 11 RQ3A.210705.001
Thank you so much!

**Comment by mistergoliath41** [comment]
> The above method works for the Pixel 4a 5G on Android 11 RQ3A.210705.001
> Thank you so much!

np. ;)
