### ISSUE TITLE
CTS working but failing safetynet on 2.0.0, was ok with 1.1.1

### ISSUE THREAD

**Issue by ivanbishop** [kdrag0n/safetynet-fix#86]
![Screenshot_20210907-121418](https://user-images.githubusercontent.com/6209755/132399304-2df74390-dd8f-46e2-a46a-c706ef30a6f4.jpg)
![Screenshot_20210907-121437](https://user-images.githubusercontent.com/6209755/132399309-aa3201df-970e-4d5e-be33-6d84b8077212.jpg)
![Screenshot_20210907-121351](https://user-images.githubusercontent.com/6209755/132399313-a1bfbfa6-1607-426b-9eca-49568a46cb5a.jpg)

**Comment by ivanbishop** [comment]
![Screenshot_20210907-122021](https://user-images.githubusercontent.com/6209755/132399518-7a812b75-d53e-47e2-88ee-45d1a7ae0467.jpg)

**Comment by Dydnlee** [comment]
Buy v2.1.0

**Comment by ivanbishop** [comment]
happy too ;) just sent youa coffee.. paypal, [ ***@***.***// | ***@***.***// ] 
how do I buy 2.1 :) ? 
Or you mean buy you more coffee ;) lol.

**Comment by Dydnlee** [comment]
https://patreon.kdrag0n.dev/buy/exclusive/safetynet-fix-v2.1.0.zip

**Comment by ivanbishop** [comment]
just signed up for $5/month on patreon, I rely on your work to save me parking tickets lol :) 
parkmobile detects rooted and wont work 
so I can park car and walk off using their app passing safetynet :) 

THANKS!!!!

**Comment by kdrag0n** [comment]
Closing due to confirmation that [v2.1.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.1.0?utm_source=github) doesn't have this issue.
