### ISSUE TITLE
Could somebody port this to heavy oem skins?

### ISSUE THREAD

**Issue by jbro129** [kdrag0n/safetynet-fix#9]
I have read #2 and am wondering if your patches could be replicated for One UI. Using https://opensource.samsung.com/ I have downloaded the source of my phones current rom. Your v1.1.1 causes my Galaxy S20+ to bootloop. Using the files provided on Samsungs open source website do you think your safety net patches could be ported to phones running One UI or other heavy oem skins like mine? Maybe developers could port your patches per device and firmware. This is assuming that the source code provided on samsungs open source page have the source code for keystore and/or libkeystore-attestation-application-id.so binaries.

**Comment by jbro129** [comment]
Obviously if the necessary source code is provided then the patches could be made per device and firmware.
This is becoming less a question and more a general comment.

**Comment by psychopathologist** [comment]
https://github.com/kdrag0n/safetynet-fix/issues/6#issuecomment-765774459

**Comment by jbro129** [comment]
> [#6 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/6#issuecomment-765774459)

Im mainly talking about the native patches in https://github.com/kdrag0n/safetynet-fix/blob/master/patches/11/sys/0001-keystore-Block-key-attestation-for-Google-Play-Servi.patch

**Comment by jbro129** [comment]
What about MSHooking the keystore function? Using A64Hook you can hook native methods during runtime and you modify what they do. It's like xposed hooking but without the need for xposed.

**Comment by psychopathologist** [comment]
> What about MSHooking the keystore function? Using A64Hook you can hook native methods during runtime and you modify what they do. It's like xposed hooking but without the need for xposed.

It'd be great the possibility of hooking, but I don't know such hooking methods you stated! Could you show me where to look for more information about these hooking techniques? Tia!

**Comment by jbro129** [comment]
> > What about MSHooking the keystore function? Using A64Hook you can hook native methods during runtime and you modify what they do. It's like xposed hooking but without the need for xposed.
> 
> It'd be great the possibility of hooking, but I don't know such hooking methods you stated! Could you show me where to look for more information about these hooking techniques? Tia!
> 
> Edit. Just saw your Unity-Substrate-Hook-Android repo!

For android hooking you can lookat these
https://github.com/Octowolve/Substrate-Hooking-Example
https://github.com/Octowolve/Hooking-Template-With-Mod-Menu
https://github.com/Rprop/And64InlineHook
https://github.com/joeyjurjens/Android-Hooking-Template

My Unity-Substrate-Hook-Android is pretty outdated but it still works.

**Comment by jkaetz** [comment]
Happy to help test any development on this.  I don't get bootloops but the launcher does repeatedly restart on my Tab S6 with Android 10 and One UI 2.5.

**Comment by kdrag0n** [comment]
Please test the new solution in #13 and continue discussion there.
