### ISSUE TITLE
Disabling MagiskHide Causes v2.1.0 to Fail SafetyNet

### ISSUE THREAD

**Issue by DavidBerdik** [kdrag0n/safetynet-fix#91]
Thank you for creating this awesome module. It's incredibly useful and really fascinating to dig through its code to see how it works under the hood.

I noticed that the changelog for v2.1.0 includes an entry that states: "Added MagiskHide features that will be removed in future versions of Magisk"

Based on this, I assumed that this version of the module would continue to bypass SafetyNet regardless of if MagiskHide is enabled or disabled, however, it seems that this is not the case on my Pixel 4a. I am not sure if this behavior is expected or universal across all phones.

Steps to reproduce:
1. With MagiskHide enabled and v2.1.0 of the module installed, check SafetyNet. It passes for me with this configuration.
2. In the Magisk app, disable MagiskHide from the settings and check SafetyNet again. It will still pass.
3. Reboot the phone and test SafetyNet again. This time, it will fail.
4. Enable MagiskHide again. This time, it will pass.

**Comment by osm0sis** [comment]
No, Magisk continues to hide its own processes and isolate things to evade detection. That hasn't been removed upstream.

**Comment by DavidBerdik** [comment]
> Magisk continues to hide its own processes and isolate things to evade detection. That hasn't been removed upstream and this module isn't replacing that at this point.

Ah okay. My apologies. What does the entry in the changelog mean, then?

**Comment by osm0sis** [comment]
It means upstream MagiskHide no longer changes any props to fool anything, so now this module does that part.

**Comment by username227** [comment]
I was able to disable magiskhide and still pass safetynet, unlike before the update. But based on what you responded, I'm not sure why, but if sure live to know...

**Comment by DavidBerdik** [comment]
> Thanks. It means upstream MagiskHide no longer changes any props to fool anything, so now this module does that part. See my PR #90 where I've updated things slightly more to match MagiskHide.

You're welcome! And thank you for the explanation. I suppose this means that in the future, it will be necessary for the module to be updated again to completely contain all the components from MagiskHide?

> I was able to disable magiskhide and still pass safetynet, unlike before the update. But based on what you responded, I'm not sure why, but if sure live to know...

Did you reboot your phone after disabling it? If not, try doing so and check it again.

**Comment by username227** [comment]
> Did you reboot your phone after disabling it? If not, try doing so and check it again.

yes, actually. several times. Without magiskhide, however, one of my more stubborn apps did detect the root; but safetynet still passed.

**Comment by DavidBerdik** [comment]
> yes, actually. several times. Without magiskhide, however, one of my more stubborn apps did detect the root; but safetynet still passed.

Interesting! Out of curiosity, what is your phone and Android version?

**Comment by username227** [comment]
> Interesting! Out of curiosity, what is your phone and Android version?

I am running on a Moto g(8) plus with Android 10. Even though the phone model is only two years old, it has always done a basic attestation, not hardware backed, although i'm not sure why that would make a difference. For now, i'm keeping magiskhide on anyway for that other app. But the awesome work of this developer leaves me hopeful that this will end up being a viable replacement.

**Comment by osm0sis** [comment]
> You're welcome! And thank you for the explanation. I suppose this means that in the future, it will be necessary for the module to be updated again to completely contain all the components from MagiskHide?

My understanding from reading the Magisk commits so far is that this part of MagiskHide will remain intact, just be renamed MagiskDeny, so USNF won't need to take that on.

**Comment by DavidBerdik** [comment]
> My understanding from reading the Magisk commits so far is that this part of MagiskHide will remain intact, just be renamed MagiskDeny, so USNF likely won't need to take that on.

Ah okay. I thought MagiskDeny was going to be a totally new thing. I did not realize that it's just a rebranding of the portion of MagiskHide that is not strictly related to bypassing SafetyNet.

I realize that this is off-topic here, but I really hope that John makes an effort to make Zygisk's API be compatible with Riru. It would be sweet if Riru-dependent modules could be used with Zygisk instead of Riru with little to no effort.
