### ISSUE TITLE
2.1.0 Breaks Fingerprint Sensor - OP8T

### ISSUE THREAD

**Issue by ohioyj** [kdrag0n/safetynet-fix#92]
Installing the latest release of safetynet-fix "breaks" the fingerprint sensor on the OnePlus 8T. After installing the finger print sensor will say hardware unavailable. Removing the module and rebooting will make the sensor function again. At first I thought it was just a coincidence, however I did get confirmation of this behavior on the 8T on the telegram group as well.  Please let me know what other information I can supply that maybe helpful, it diagnosing this issue. I'll be happy to help.

**Comment by osm0sis** [comment]
I already have a fix submitted since a couple hours after release last night, so hopefully @kdrag0n can review, merge and release 2.1.1 with the fix shortly. 👍

**Comment by ohioyj** [comment]
You already tested this on your 8T, but I can confirm this also works / fixes my 8T as well.

**Comment by osm0sis** [comment]
You should leave this open. It'll automatically close when my fix is merged

**Comment by Killer-931** [comment]
Am getting an issue with my Fingerprint Scanner not working, I'm also on a OnePlus 8T, how do I fix this?
![Screenshot_2022-05-21-05-15-08-20_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/42481122/169596640-961369e7-7939-41f6-97be-a277bd0c0b29.jpg)

**Comment by osm0sis** [comment]
It's fixed in the code here, but it hasn't been released. You can add it manually for now.

**Comment by Killer-931** [comment]
https://user-images.githubusercontent.com/42481122/169601751-af4aa53e-7106-438d-9c82-3cadabc75a85.mp4

What do and Please show don't tell, I am extremely dumb.

**Comment by osm0sis** [comment]
Nope, I already have, read back to my last reply.

**Comment by Killer-931** [comment]
> It's fixed in the code here, but it hasn't been released. You can add it manually for now.

Explains everything I need to know.

https://user-images.githubusercontent.com/42481122/169606632-64544f89-4d12-4cb4-86c2-675dcd919b6d.mp4

**Comment by osm0sis** [comment]
🙄

https://github.com/kdrag0n/safetynet-fix/issues/92#issuecomment-919494445

**Comment by Killer-931** [comment]
> 🙄
> 
> No, read. My last reply: [#92 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/92#issuecomment-919494445)

And read Mine. Please *Show* don't *Tell*.

You have screen recorder on your OnePlus too. If that's too much to ask, I'll go without or try and figure it out.

Visual aid would be epic.

**Comment by Killer-931** [comment]
And and putting these two files into the non Riru version, 2.2.1 doesn't fix the issue.
![Screenshot_2022-05-21-07-22-10-11_2602b93dc3ef59eeb51bac049073361e](https://user-images.githubusercontent.com/42481122/169612595-c850141a-9ba2-4d5f-bbec-dd50d3539c6d.jpg)

**Comment by osm0sis** [comment]
I only use Zygisk, should be the same though

**Comment by Vladi69** [comment]
> I only use Zygisk, should be the same though

@osm0sis I am sorry, but I am not able to solve this issue. What I did is to overwrite **service.sh** and **system.prop** in the following modules:
- safetynet-fix-v2.1.0.zip (flashed togerther with riru and deactivating zygisk)
- safetynet-fix-v2.2.1.zip
I also flashed **safetynet-fix-v2.1.3.zip** (flashed togerther with riru and deactivating zygisk) and also **safetynet-fix-v2.2.1.zip** without replacing the files, otherwise I receive an error when flashing.

None of them worked for me.
As I also have an OP8T, can you please share your modded module working with Zygisk, please?
You also helped me a lot in the AAwireless implementation, I am in that group, my respect to you.

Thank you!

**Comment by osm0sis** [comment]
It worked for @ohioyj, who created this issue, so I'm not sure what to tell you. Personally I'm not updating to OOS12 at all... At least not until they get their shit together and release usable kernel source.

**Comment by osm0sis** [comment]
Oh wait, duh, you guys this is the old issue.. The one from OOS12 is here: https://github.com/kdrag0n/safetynet-fix/pull/164
