### ISSUE TITLE
Safetynet without riru

### ISSUE THREAD

**Issue by skelletR** [kdrag0n/safetynet-fix#96]
Hi just now i updated to magisk 23 and now i see the old version 1.1.1 have it not working anymore, i want updated to latest but i read need riru module first, i don't really want to install this

**Comment by kdrag0n** [comment]
The module was migrated to Riru in order to fix issues that are unavoidable with the old approach, as far as I know. As a result, there are no plans to offer a version that uses the old approach, but there's nothing to update for it anyway (unless you're on Android 12).

**Comment by skelletR** [comment]
> The module was migrated to Riru in order to fix issues that are unavoidable with the old approach, as far as I know. As a result, there are no plans to offer a version that uses the old approach, but there's nothing to update for it anyway (unless you're on Android 12).

Oh understand, i have android 10
