### ISSUE TITLE
Shouldn't this Module fool root detection in apps?

### ISSUE THREAD

**Issue by b1ackfa1c0n** [kdrag0n/safetynet-fix#98]
So first time I heard about this Module, I heard that It helps bypassing safteynet api which is used by apps for root detection, but after I have installed the version that supports one ui, It successfully bypassed safteynet ap In magisk, but this didn't help with avoiding root detection, and banking apps still detects root. Is It something that I have done wrongly, or Is It something that I don't quite understand, thank you for your hard work.

**Comment by Didgeridoohan** [comment]
It's the latter...

Most apps like that don't actually use SafetyNet and have their own versions of root detection implemented. Could be a number of things, but the most popular recently have been detecting the Magisk app (it's possible to detect it even when repackaged with a random name, just a little bit harder). There are also many other ways...

**Comment by ArbitraryFox** [comment]
It doesn't. My bank app detects Magisk even with the app deleted.

**Comment by Didgeridoohan** [comment]
Detecting root/a compromised device isn't only about detecting the Magisk app. I only said that's one of the more popular apporaches lately. There are tons of things to look for, and Magisk is just one (and the Magisk internals are way more easy to hide than the Magisk app).

**Comment by b1ackfa1c0n** [comment]
So does anyone have an Idea for how to prevent banking apps from detecting root?

**Comment by Didgeridoohan** [comment]
Like I said, could be a whole number of things. I suggest you close this issue (since it has nothing to do with the USNF module) and then take a look here (where I've collected a few tips on how to maybe get things working):
https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps

**Comment by kdrag0n** [comment]
This module is only meant to bypass SafetyNet. Other root detection mechanisms are out of scope.
