### ISSUE TITLE
S20 with safetynet-fix 2.1.1 not passing CTSProfile

### ISSUE THREAD

**Issue by lulle2007200** [kdrag0n/safetynet-fix#99]
I am using a Galaxy S20 running Lineage 18.1 and Magisk 23.0. 
Tried safetynet-fix 2.1.1 to pass safety net, but the cts check keeps failing. 
Not sure if im missing something or if it just doesnt work.

**Comment by kdrag0n** [comment]
GitHub issues are for bug reports, not support. Please try the following steps in order: https://t.me/proton_projects/26689
